### ISSUE TITLE
device.discover() ?

### ISSUE THREAD

**Issue by farhanito** [mjg59/python-broadlink#1]
noob question,

device.discover() didn't returns anything. what am i missing?

> osmc@osmc:~$ python
> Python 3.4.2 (default, Oct  8 2014, 14:38:51)
> [GCC 4.9.1] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import broadlink
> >>> device = broadlink.rm2()
> >>> device.discover()
> >>>

regards,

**Comment by mjg59** [comment]
Do you have a Broadlink rm2 on the same network as the machine you're running discover() from?

**Comment by farhanito** [comment]
yes, both on the same network

**Comment by mjg59** [comment]
What timezone are you in?

**Comment by farhanito** [comment]
GMT+7


Get Outlook for Android






On Mon, Sep 19, 2016 at 10:30 AM +0700, "Matthew Garrett" <notifications@github.com> wrote:












What timezone are you in?

**Comment by mjg59** [comment]
Ok - the bit that says:

    packet[0x08] = 0xf9
    packet[0x09] = 0xff
    packet[0x0a] = 0xff
    packet[0x0b] = 0xff

Can you change that to:

    packet[0x08] = 0x07
    packet[0x09] = 0x00
    packet[0x0a] = 0x00
    packet[0x0b] = 0x00

and see if it works any better?

**Comment by farhanito** [comment]
Ok. Here's what I got.. 
[http://i.imgur.com/sUFSLaf.jpg](http://i.imgur.com/sUFSLaf.jpg)

**Comment by farhanito** [comment]
changed to Python2.7, everything seems works now

regards,

**Comment by mjg59** [comment]
Oh, cool - I'll fix up the timezone code and try to make it work under Python 3. Thanks for testing!

**Comment by LinZihong** [comment]
My time zone is GMT+8 and I changed the bytes to
`packet[0x08] = 0x08
packet[0x09] = 0x00
packet[0x0a] = 0x00
packet[0x0b] = 0x00`
according to my guess, but it didn't work. Am I wrong?
