### ISSUE TITLE
broadlink.discover - debugging the discovery

### ISSUE THREAD

**Issue by psyciknz** [mjg59/python-broadlink#111]
I'm trying to add some code to broadlink-mqtt to deal with multiple devices (multiple rm2 in this case).

I have a machine with 2 nics, one for my regular lan (192.168.10) , and another (192.168.100) for IOT devices.

If I issue a 
```
import broadlink
broadlink.discover(timeout=20,local_ip_address='192.168.100.11')
```

It never finds the two devices (at 100.12 and 100.13).  I know I can explicitly set up two hosts, but I'd like to get the discover process working.

Any guidance.

**Comment by felipediel** [comment]
Hello. When the device is locked, it cannot be discovered with broadcasting. You need to say hello to the device:
```python3
>>> import broadlink as blk
>>> d = blk.hello('192.168.100.11')
```
If you want to unlock it:
```python3
>>> d.auth()  # You need to auth first
>>> d.set_lock(False)
```

Now you will be able to discover the device:
```python3
>>> devs = blk.discover(timeout=10, discover_ip_address='192.168.100.255')
>>> devs
```
Closing, since its not a problem to be solved in our code base.
