### ISSUE TITLE
Is there any way to have the energy monitoring of the sp2？

### ISSUE THREAD

**Issue by xyyaya** [mjg59/python-broadlink#114]
Is there any idea or method to get the energy monitoring infomation of the sp2?

**Comment by VooDooN1** [comment]
I need the same functionality for SP3S. I don't know how to extract bytes with power information from payloads.

**Comment by eschava** [comment]
I've implemented energy monitoring for SP3S in my clone of the python-broadlink (and pulled request of course) but there is a doubt that it will work for SP2 in the same way

**Comment by VooDooN1** [comment]
**xyyaya**, can you test the code from **eschava** for SP2? I have SP3S and this code works fine, but SP2 of my friend (0x2711) does not receive the energy value. Thank you! We use the same algorithm for PHP-Broadlink library in the MajorDoMo project.
