### ISSUE TITLE
Smart Plug SP3 is "Unkown device"

### ISSUE THREAD

**Issue by makiolo** [mjg59/python-broadlink#115]
Hi,

I bought this smart plug because I saw that this library has managed to control it with reverse engineering.

My SP3 is identified as 0x947A (unknown), and I have tried to force the class "sp2" to be created, but the switch does not work, and not power consumption.

How can I help by sending sniffing wifi while using the mobile app?

**Comment by eschava** [comment]
In my case, sp2 class works OK for SP3S device (just for power state of course, not energy monitoring)

**Comment by eschava** [comment]
Also, I've pulled request for get_energy method for SP2 devices

**Comment by makiolo** [comment]
Thank you, I will test your pull request.
