### ISSUE TITLE
Allow long WLAN key (WPA2-PSK)

### ISSUE THREAD

**Issue by Schack17** [mjg59/python-broadlink#116]
At the moment only WLAN keys with max. 32 chars are possible.
Can you enable the official limit of 63 chars?

**Comment by ruimarinho** [comment]
I just got one of their most recent units (RM3 mini) and I can confirm this bug is still there - it appears to be a firmware issue and not related to python-broadlink. The same issue is present using the e-control app.

**Comment by felipediel** [comment]
Closing, since the problem cannot be solved in our code base.
