### ISSUE TITLE
RF send_data() only works first time

### ISSUE THREAD

**Issue by kelvl** [mjg59/python-broadlink#12]
I have a RM2
Seeing an issue where if I use send_data() for my RF switch, only the initial call works. 
After that it seems like the controller enters a state that ignores subsequent calls.

```python
devices = broadlink.discover(timeout=5)
devices[0].auth()
devices[0].enter_learning() 
# I press ON on my remote
on = devices[0].check_data()
devices[0].enter_learning()
# I press OFF on my remote
off = devices[0].check_data()
devices[0].send_data(on) # this works - LED on RM2 turns ON for a bit and my RF switch turns ON
devices[0].send_data(off) # this doesn't - no LED on RM2, RF switch doesn't turn OFF
```

However, the following scenario works

```python
# discovery, auth and learning is same as previous example

# this works - LED on the RM2 turns ON for a bit and my RF switch turns ON
devices[0].send_data(on) 

# Use the official broadlink app on my phone, 
# trigger any RF button (doesn't need to be for the specific switch 
# that I am using), LED on RM2 turns ON for a bit

# now this works exactly as expected, LED on RM2 turns ON for a bit and 
# my RF switch turns off
devices[0].send_data(off) 
```

I suspect that the broadlink app is sending some kind of "reset" command after it triggers the RF signal while python-broadlink is missing that "reset" causing the consecutive send_data() calls to fall. 

Any ideas?

I might try and see if i can get some packet dumps from my android phone's broadlink app to see if there are any additional packets sent after RF data is sent

**Comment by mjg59** [comment]
This should work with the patch I just merged from @msh100
