### ISSUE TITLE
Rolling Code

### ISSUE THREAD

**Issue by ranathan14** [mjg59/python-broadlink#123]
Hi,
I have a rolling code remote control for a garage.
Is it possible use this library?
Tnx

**Comment by matangg** [comment]
@ranathan14 the library merely let's you record and replay IR or RF packets. It won't help you crack the rolling code algorithm. However, the fact that your remote control has a rolling code doesn't necessarily mean your gate enforces the rolling code part. Many gates don't enforce the rolling code for convenience. You can try recording the RF transmission and replay it using broadlink and see if it works. If this is a gate you own you can probably turn off the rolling code enforcement. However, this will compromise the security of your gate.
