### ISSUE TITLE
RM mini 3 learning mode

### ISSUE THREAD

**Issue by utamir** [mjg59/python-broadlink#126]
Learning mode and read data is not working for RM mini 3 device

Just to ensure that this is not coding issue - device white led is not turning on and there is an error in response packet

**Comment by blapid** [comment]
Adding my 2c: I had issues entering learning mode for my RM mini 3 as well, when trying to do it with the python REPL. 
However, using the CLI worked fine.

**Comment by utamir** [comment]
For me it does not work with CLI either

**Comment by roondar** [comment]
I confirm it's working with CLI.

**Comment by felipediel** [comment]
Hello. You need to authenticate first.
```python3
import broadlink as blk
d = blk.hello('192.168.0.16')  # Example device
d.auth()
d.enter_learning()
```
That's probably where the error came from. Old issue, now we raise an exception. Closing.
