### ISSUE TITLE
how to assign mac address and ip

### ISSUE THREAD

**Issue by tyjtyj** [mjg59/python-broadlink#13]
Anyway can speed up discovery by assigning the mac address and ip address manually. 

Just 1 device with me and there is no need to discover each time as the mac and ip address always the same. 

I am not python expert. Any example would be great.

**Comment by 264768502** [comment]
device = broadlink.device(host=host, mac=mac)
you need convert mac string to bytearray

**Comment by mjg59** [comment]
device = broadlink.device(host="192.168.1.1", mac=bytearray([0x01, 0x02, 0x03, 0x04, 0x05, 0x07]))

should work, for example.

**Comment by illxi** [comment]
device = broadlink.device(host=("your ip", 80), mac=bytearray([0x01, 0x02, 0x03, 0x04, 0x05, 0x07]))

mac is in reverse order.

**Comment by jcoudrais** [comment]
for me, mac address is in the right order... 

But I get freezes on python randomely... Any idea ?

**Comment by tyjtyj** [comment]
Test this works 
device = broadlink.device(host=("192.168.1.1",80), mac=bytearray.fromhex("aa bb cc dd ee ff"))

Mac does not need to be reverse. Thanks all for help

**Comment by tyjtyj** [comment]
This stopped working after recent update

This works 
devices = broadlink.discover(1)
device = devices[0]

But this does not work anymore
device = broadlink.device(host=("192.168.1.10",80), mac=bytearray.fromhex("b4 43 0d d1 00 00"))

**Comment by mjg59** [comment]
Yes, sorry, the move to properly subclassing different device types means that the generic device class is no longer useful - you'll need to express the type by creating the appropriate class.
