### ISSUE TITLE
RM PRO+  cant get temperature

### ISSUE THREAD

**Issue by dimagoltsman** [mjg59/python-broadlink#133]
i have a probably new device, model: RM PRO+
and getting temperature always show 0.0

**Comment by khanwhlee** [comment]
I have the same prob as well...

**Comment by dimagoltsman** [comment]
can be closed... i have a device that says "Rm pro +", the thing with the plus is that it doesnt have temp sensor

**Comment by antonraharja** [comment]
Hi @dimagoltsman 

Thanks for the info, was looking for this. Can you share where did you get the info, or maybe you've tested it ? Thanks.

**Comment by dimagoltsman** [comment]
@antonraharja 

i talked to Broadlink directly.

their answer:

> Dear Customer,
Pls kindly note the device of RM pro+ don't have the temp sensor function, so it can't help show the temp on it, thanks!

**Comment by Dustyfrogz** [comment]
you are lucky, I can't use the rm pro + with jeedom or domoticz

**Comment by Fusseldieb** [comment]
Why did they take this awesome function away? Bummer.

**Comment by felipediel** [comment]
Closing, since it is not a problem to be solved in our code base.
