### ISSUE TITLE
Packet counter: counts too high

### ISSUE THREAD

**Issue by a-lurker** [mjg59/python-broadlink#137]
On this page:
https://github.com/momodalo/broadlinkjs/blob/master/index.js#L367

`device.prototype.sendPacket = function( command, payload){
    this.count = (this.count + 1) & 0xffff;
var packet = Buffer.alloc(0x38,0);`

The count, which appears to be used to match transmitted messages to their associated replies, can cause problems with 'RM2 Pro Plus2' when transmitting IR sequences.

Specifically, if the count is >= 0x7ffe the IR sequence will not be transmitted. Presumably this is some negative wrap around problem in the Broadlink device. Just limiting the count to a max of 255 ie just ANDing with 0x00ff resolves this problem. 0x0fff could probably also be used.

**Comment by felipediel** [comment]
When the packet count is >= 0x7FFF the device doesn't reinterpret duplicate packets. We clamped the counter between 0x8000 and 0xFFFF to take advantage of this behavior: https://github.com/mjg59/python-broadlink/pull/486. Thank you!
