### ISSUE TITLE
[Question] Is this support SP mini3?

### ISSUE THREAD

**Issue by fcying** [mjg59/python-broadlink#153]
I saw there is not  SP mini3 inside devtype, is this support SP mini3?

**Comment by Nightreaver** [comment]
New devices might have different device-type, but the general support for new devices might be added if you can provide more information

**Comment by tenhow** [comment]
how to find the device type? I get mac and ip, but no device type

**Comment by Donkeyes** [comment]
sp mini3 cannot work.I put the device type into sp2,but not work. The device can be finded .

**Comment by felipediel** [comment]
Hello. [These](https://github.com/mjg59/python-broadlink/blob/b33bbdbbcf1270fb77f346f0e003273247d3ff2f/broadlink/__init__.py#L17-L111) are the supported types. I am improving the documentation to show the models on top.
