### ISSUE TITLE
[Question] - get_energy for SP3 smart plugs

### ISSUE THREAD

**Issue by wuid24** [mjg59/python-broadlink#154]
Hi , 

first : its a wow !!! thanks for the developers that enabled this python based controlling - the broadlink app is miserable, and I cant count on the IFTT.  

questions : 
1. 
my questions is for the support of getting the energy with SP3 - can anyone verify my thoughts that this option isn't hardware supported in this model ? 

2. 

looking at part of the details when discovering devices it seems that i'm getting gibberish - unrecognised string, i.e: 

![image](https://user-images.githubusercontent.com/37136503/37090496-4cfa6eb8-220d-11e8-9db6-72f50f97c042.png)

I want to be able to extract the mac address so I can assign it whether it changed an ip or not.

thanks again,

**Comment by eschava** [comment]
1. Please check sp2.get_energy() method. sp2 class is used for sp3 devices
2. use` '_'.join(format(s, '02x') for s in device.mac[::-1]` instruction  to show device.mac as human-readable string

**Comment by wuid24** [comment]
thanks for #2

As for #1 i've tried it , and always get "0.01" so it seems that sp3 does not support energy readings..

**Comment by Nightreaver** [comment]
energy is only supported for SP3S not for regular SP3
but instead SP3 has "night light" option that SP3S has not

**Comment by wuid24** [comment]
ok thank you
