### ISSUE TITLE
Backup - Import and Export Configuration

### ISSUE THREAD

**Issue by xSeekTruthx** [mjg59/python-broadlink#162]
With all the available commands in broadlink_cli I am surprised to see there is no way to backup the learned remote configurations. I have an RM3 mini that works great with this, however I'd like to save the all the remotes/config to my computer, with the ability to restore it to itself or an RM Pro when I upgrade the RM3 Mini. Any possibility of adding an import/export command?

Thank you

**Comment by xSeekTruthx** [comment]
Just realized all the files are kept in python-broadlink duh... Thanks :)

**Comment by msteingr** [comment]
is there a way to back up easily?
