### ISSUE TITLE
RF Code Sends Multiple Times

### ISSUE THREAD

**Issue by xSeekTruthx** [mjg59/python-broadlink#163]
Used e-control and plugin to learn all the correct RF codes. 6 different devices, 2 different brands. However, the RM Pro randomly sends the RF code as much as 5 times. I can tell when watching the orange light, how there is a slight blip each time it cycles the code. My main RF units only use 1 button for On and Off, and it ends up creating a light show! E-control app randomly does the same thing. Any way to force the unit to send the data one time? Like a send once, best effort kinda deal from terminal?

(Just upgraded firmware, issue still exists)

Thank you!

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/486. Thank you!
