### ISSUE TITLE
Add support for Clas Ohlsson OEM branded SP3

### ISSUE THREAD

**Issue by ooo89** [mjg59/python-broadlink#167]
Add "devtype == 0x7D00" to point to a sp2 constructor to add support for the Clas Ohlsson OEM branded SP3 device.

Line 25 "elif devtype == 0x753e: # SP3"

could become:
"elif devtype == 0x753e or devtype == 0x7D00: # SP3"

**Comment by Nightreaver** [comment]
You can create a pull request for this change

**Comment by ooo89** [comment]
Done, Was easier than expected. :)
