### ISSUE TITLE
Support for S2 hub in the Alarm link

### ISSUE THREAD

**Issue by gianpyc** [mjg59/python-broadlink#168]
The current library supports the S2 hub alarm kit? 
http://www.dx.com/it/p/original-broadlink-2017-new-design-s2-hub-security-suit-white-916484819#.WruLwGZaadv

Or is it possibile to use the same connection method for the S1C?

Thanks

**Comment by felipediel** [comment]
S1C and S2K are the same internally and can be controlled with the S1C class.
