### ISSUE TITLE
RP3 hung after 60-200 minutes running broadlink A1 and or SP3

### ISSUE THREAD

**Issue by Spinke** [mjg59/python-broadlink#170]
I can read all sensors of the A1 module correctly only after 10-200 minutes domoticz stops responding after a restart it will work for some time and will hung up the system within 10-200 minutes.
Any suggestions where to start looking ?

The second issue is with the SP3 plugin, it will switch on and off correctly but not measure the power.
This plugin will also hung up the system within 10-200 minutes  

Thanks in advance

**Comment by felipediel** [comment]
Closing, since the problem cannot be fixed in our code base.
