### ISSUE TITLE
RM Pro+ compatibility

### ISSUE THREAD

**Issue by Komagain** [mjg59/python-broadlink#174]
I am trying to use the package with my RM Pro+ (RM03) for few weeks,
I have never been able to make it works,
I am wondering if the hardware is compatible with the package,
I have seen this website [http://www.paulhibbert.co.uk/2017/11/24/a-complete-guide-to-connecting-the-broadlink-rm-pro-and-broadlink-blackbean-to-alexa/] (not sure it is related):
Which models are affected and how are they affected?:

> MODELS ARE AFFECTED AS FOLLOWS:
> RM2 : Unaffected
> RM2+ : Does not work with the ‘official skill work around’ but does work with RM plugin method (requires firmware change)
> RM03 : does not work with either method
> RM PRO+ : does not work with either method

**Comment by torinnguyen** [comment]
RMPlugin works with all devices now.

**Comment by Dustyfrogz** [comment]
with the new 4.1.0 plugin version you can learn only one signal.

**Comment by atze09** [comment]
> RMPlugin works with all devices now.

You mean it should work with RM2 Pro PLUS3 also?

**Comment by felipediel** [comment]
Closing old issues. [These](https://github.com/mjg59/python-broadlink/blob/b33bbdbbcf1270fb77f346f0e003273247d3ff2f/broadlink/__init__.py#L17-L111) are the models we support now.
