### ISSUE TITLE
Pyaes encryption for S1C

### ISSUE THREAD

**Issue by lily148** [mjg59/python-broadlink#176]
Hi,

I notice the S1C code is using only Crypto to decrypt bytes.
I try to convert to pyaes but it fail. Anyone have idea?

- Original
aes = AES.new(bytes(self.key), AES.MODE_CBC, bytes(self.iv))
- My code for pyaes       
aes = pyaes.AESModeOfOperationCBC(self.key, iv = bytes(self.iv))

- Original
payload = aes.decrypt(bytes(response[0x38:]))
- My code for pyaes
payload = b"".join([aes.decrypt(bytes(response[i:i+16])) for i in range(0, len(response[0x38:]), 16)])

I am sure somewhere I miss but don't know where.....
Anyone can help?

**Comment by Nightreaver** [comment]
We already have some pyaes implementation here (https://github.com/mjg59/python-broadlink/blob/master/broadlink/__init__.py#L178)

Maybe you can check there?

And if you commit, try similar approach with supporting both ... pyaes and crypto

**Comment by felipediel** [comment]
Closing, since the problem cannot be fixed in our code base.
