### ISSUE TITLE
TypeError: __init__() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by felinh** [mjg59/python-broadlink#184]
Hello
Scanning network for Broadlink devices works
but after calling  

#!/usr/bin/python
 import broadlink
import time
import sys 
device = broadlink.rm(host=("xxx.xxx.xxx.xxx",80), mac=bytearray.fromhex("xxxxxxx"))
--
console displays
**TypeError: __init__() takes exactly 4 arguments (3 given)**

what is going wrong?
![image](https://user-images.githubusercontent.com/38888761/39481777-d88dc0a8-4d6c-11e8-8765-b152669cd6fe.png)

**Comment by andrez7** [comment]
Hi Felinh 

Try with broadlink.rm(IPAddress, Port, MACAddress, Timeout)
In my project I added the 4th arguments and It works. p.e Timeout = 30

**Comment by AntonLevi** [comment]
import broadlink
import time
import sys
ip = "192.168.1.33"
port = 80
mac = "b44345455555"
timeout = "30"
device = broadlink.rm((ip,port), mac, timeout)

**Comment by felinh** [comment]
thanks guys, I do confim the timeout argument was missing.
It works now.
PS: source [here](http://domo-attitude.fr/broadlink-rm-promini-domoticz/) to be updated.

**Comment by albebert** [comment]
> 
> 
> thanks guys, I do confim the timeout argument was missing.
> It works now.
> PS: source [here](http://domo-attitude.fr/broadlink-rm-promini-domoticz/) to be updated.

Hello, how have you added the timeout arugment please ? tried some things but no luck :( 

thanks
