### ISSUE TITLE
SC1 Device

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [mjg59/python-broadlink#197]
why does he put:
 class S1C (device):
  "" "
  Its VERY VERY VERY VERY DIRTY IMPLEMENTATION of S1C
  "" "
??
It does not work well? Can it be used normally with SC1 devices?

**Comment by FelipeSanchezCalzada** [comment]
I forgot the most important thing: 
Thanks for the work!

**Comment by fantomnotabene** [comment]
SC1 (relay) and S1C (alarm kit) are different things

**Comment by felipediel** [comment]
We've already cleaned up the S1C (alarm kit) class. The SC1 (relay) can be controlled with the sp2 class. Closing.
