### ISSUE TITLE
Domoticz Beta crash

### ISSUE THREAD

**Issue by cbartetzko** [mjg59/python-broadlink#204]
I'm running Domoticz Beta on Raspberry Pi and would love to use this wonderful Plugin.
However when installing and running the Plugin, Domoticz instantly crashes with "Segmentation Fault"
and can only be restarted after disabling the plugin. There are a lot of discussions ongoing regarding this problem in the Domoticz forum since quite a wihile, but no solution so far.

**Comment by felipediel** [comment]
Closing, since it is not a problem to be solved in our code base.
