### ISSUE TITLE
New MP1 type

### ISSUE THREAD

**Issue by Ilafebig** [mjg59/python-broadlink#207]
Hi Matthew
Got me a second MP1 from China from the same shop that I got the first one from.
But it had 3 power and 2 2.4mA USB ports instead of 4 power.
(it was not an MP2 where you only can on/off all of the plugs)
So I found out that there are 2 types of MP1s
The  Broadlink MP1-1K4S that the library supports. And the Broadlink MP1-1K3S2U that the library do not support.
So I fiddled around and found the device type ( print (responsepacket[0x34]) print (responsepacket[0x35]) did the trick) and its 0x4F65

So now I have          
mp1: [0x4EB5,  # MP1
                0x4F65,  # MP1 USB
                0x4EF7   # Honyar oem mp1
                ],   

in broadlink/__init__.py
and both power bars work. (the 2 usb ports are port number 4)

The only issue I have is that broadlink.discover(timeout=5) is to little timeout=10 is better but I use 15 just in case sometime it only find one bar. And it seems to be random what bar is index 0 and 1
Is there a way to see the mac address from the library so you can identify what bar is index 0 and 1 ?

And thanks for a great library. :)

Yours Il kjæmpe Afe big :)

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/386. Thank you!
