### ISSUE TITLE
Version number as string, not floating point (e.g. 0.90000000000000002)

### ISSUE THREAD

**Issue by hogi1200** [mjg59/python-broadlink#208]
I've had a problem using broadlink with home assistant that I wanted to share.
Home assistant wants to install broadlink version 0.9.0.
The installation itself works fine, but after installation pip lists the package as broadlink==0.90000000000000002.
Because of this, home assistant thinks that the required version is still missing.

I have traced the problem to the code `version=0.9` in setup.py file: https://github.com/mjg59/python-broadlink/blob/58a571400977609c650ed8299c2d7fc3bbc08323/setup.py#L22
It is given as floating point number, not as string. At least on my system (Synology NAS) this leads to the weird version 0.90000000000000002. I guess not everyone is affected by this, otherwise it would probably be fixed already.
As a workaround I made a local change in setup.py to `version='0.9'` and installed it manually with pip. After this, `pip list` correctly showed broadlink==0.9 and home assistant did not complain anymore.

=> For the next release, please make the version number as string.
Thanks!

**Comment by Danielhiversen** [comment]
Fixed
