### ISSUE TITLE
sp2/sp3 device status not working.

### ISSUE THREAD

**Issue by dimovnike** [mjg59/python-broadlink#209]
I have a device which is discovered as type 0x2733, the turn/turnnl on/off commands work but status doesn't. I played a bit with the code and produced a successful patch, would you accept a pull request? And if yes, how long does it take for the change to propagate to the hass.io distro?

**Comment by felipediel** [comment]
Hi @dimovnike. Has this problem been resolved? If not, I would be grateful to see your patch.

**Comment by felipediel** [comment]
Is [this](https://github.com/dimovnike/python-broadlink/commit/73fc5fc4b97f3d62fee7b25a62622cd20bd586de) the patch? If so, it is already merged. Thank you!

**Comment by dimovnike** [comment]
yes, that's the patch, thank you.
