### ISSUE TITLE
Broadlink CLI not working for Broadlink RM3 Mini

### ISSUE THREAD

**Issue by ktaragorn** [mjg59/python-broadlink#213]
My device is getting discovered/detected as of type `0x27C2` which doesnt seem to be recognized, and thus most methods dont work. I am able to force the CLI to treat it as `0X2712` and get it to do `--learn` atleast though

**Comment by valley-fordham** [comment]
I have the same device id, but still get an enter_learning error with the above change

`Traceback (most recent call last):
  File "broadlink_cli", line 123, in <module>
    dev.enter_learning()
AttributeError: device instance has no attribute 'enter_learning'`

**Comment by felipediel** [comment]
This has already been resolved. Closing.
