### ISSUE TITLE
new device 0x7d0d

### ISSUE THREAD

**Issue by ninstein** [mjg59/python-broadlink#215]
broadlink_cli --device "0x7d0d 192.###.#.### d##########8" --turnon
Traceback (most recent call last):
  File "broadlink_cli", line 154, in <module>
    dev.set_power(True)
AttributeError: device instance has no attribute 'set_power'

**Comment by ninstein** [comment]
product link（天猫精灵定制版）:https://detail.tmall.com/item.htm?spm=a230r.1.14.15.683585edWvRuLt&id=44737476504&ns=1&abbucket=5&skuId=3428979046412

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/228. Thank you!
