### ISSUE TITLE
Error "not support x86intrin.h header"

### ISSUE THREAD

**Issue by vinhpaint** [mjg59/python-broadlink#217]
Install python-broadlink: python setup.py install (Synology DS418)
...
Writing /tmp/easy_install-EfKCRo/pycryptodome-3.6.6/setup.cfg
Running pycryptodome-3.6.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-EfKCRo/pycryptodome-3.6.6/egg-dist-tmp-6fVDD7
Testing support for x86intrin.h header
Target does not support x86intrin.h header
warning: no files found matching '.separate_namespace'
Testing support for 128-bit integer
Target does not support 128-bit integer
Testing support for intrin.h header
Target does not support intrin.h header
Testing support for cpuid.h header
Target does not support cpuid.h header
Testing support for posix_memalign
Target does not support posix_memalign
Testing support for memalign
Target does not support memalign
Warning: compiler does not support AESNI instructions
Warning: compiler does not support CLMUL instructions
unable to execute '/usr/local/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-ccache-gcc': No such file or directory
error: Setup script exited with error: command '/usr/local/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-ccache-gcc' failed with exit status 1
root@admin:/usr/local/python-broadlink# /opt/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
...
help me

**Comment by Danielhiversen** [comment]
We are not using pycryptodome anymore. Try the latest version of the library
