### ISSUE TITLE
OpenHAB Broadlink RM2 initializing Status instead Online

### ISSUE THREAD

**Issue by lengyej** [mjg59/python-broadlink#222]
Hello OpenHAB Guru-s, I have a problem with Broadlink RM2 binding. Auth.code and IV code was typed into a req.fields. OK. But the status of the item is staying on 2Initializing” and do not will be online. When I press the Radiobutton “comand” at the channels, I get “Error404 not found” message right bottom on the screen. Can anybody help me?

Screenshots here: https://paper.dropbox.com/doc/Help-me-pease--AUPIK4GHwrSwFGVJVdBHGazWAg-VWoI7D6vVYxjd6qB2l4o0

**Comment by felipediel** [comment]
Closing, since it is not a problem to be solved in our code base.
