### ISSUE TITLE
send_packet

### ISSUE THREAD

**Issue by smacker-a** [mjg59/python-broadlink#225]
When sending packet to the device, the header bytes 0x24 and 0x25 must be the Device Code ( Devices struct), these were received after HELLO (0x6 at 0x26) command.  Thats what I am observing after some packet sniffing between the device and the E-Control APP. Same situation between the device and the cloud.
But nevertheless, the device (RM Mini) is work with any other values and will always return your values.

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/317. Thank you!
