### ISSUE TITLE
static IP as argument instead of discover possible?

### ISSUE THREAD

**Issue by AloisKlingler** [mjg59/python-broadlink#226]
Hi,

I used python-broadlink 0.5 in some scripts with lines like this:
mac=binascii.hexlify(b'34ea34f54336')
devices=broadlink.sp2(('192.168.0.248',80),mac)
auth = devices.auth()
state = devices.check_power()

worked flawless until I updated recently to most current lib and recognized the scripts not working any more:
    devices = broadlink.sp2(host=('192.168.0.248',80), mac=mac)
TypeError: __init__() missing 1 required positional argument: 'devtype'

So I rewrote to:
devices = broadlink.discover(timeout=2)
auth = devices[0].auth()
state = devices[0].check_power()

I recognized that script execution time now takes much longer than before:
# time ./smartplug.py check

real    0m6.195s
user    0m2.730s
sys     0m0.910s

With lib version 0.5 and communication with IP and MAC it needed about half the time.

I was wondering if there is a possibility to try the old format if it is faster.

I also saw importing broadlink lib already takes about 4 seconds:
#time ./tst.py

real    0m3.922s
user    0m2.630s
sys     0m0.910s

Is it possible to only import a subset of the lib to save time? I am using only One single SP2 smartplug.
I am on a raspberry pi with python 3.4

Thanks!

Best regards
Alois

**Comment by AloisKlingler** [comment]
nobody here who can help?

**Comment by gpenverne** [comment]
Hi!

Did you try with
```python
devices = broadlink.sp2(host=('192.168.0.248',80), mac=mac, devtype="SP2")
```
?

**Comment by felipediel** [comment]
Hi. You can use broadlink.hello() for direct discovery, example:
```python3
import broadlink as blk
d = blk.hello('192.168.0.16')  # Your device.
```
Closing.
