### ISSUE TITLE
led blinks when requesting energy 

### ISSUE THREAD

**Issue by jeanantoine** [mjg59/python-broadlink#229]
Hello,

when sending a get energy request with broadlink_cli (option --energy) the led of the SP3S flashs for a short time. It is a little annoying when using the smart plug in a bedroom. Is there a way to stop the flashing (when requesting other commands there is no flashing, and the energy reading with the Broadlink app do not flash to)?

**Comment by felipediel** [comment]
Hi. The IHC app sends exactly the same packet. Is there a chance that the blinking LED is caused by device.auth() and not device.get_energy() specifically?

**Comment by felipediel** [comment]
I will consider this case closed, if you still have the issue please reopen it.
