### ISSUE TITLE
check_power_raw may has no return value

### ISSUE THREAD

**Issue by hawkefly** [mjg59/python-broadlink#236]
This is the logic in check_power_raw()
https://github.com/mjg59/python-broadlink/blob/db2dec13e1a628382d1544f49a86b5082d8ed7fd/broadlink/__init__.py#L339-L346
Because some network stability problem, err may not equal to 0, in this situation , the check_power_raw() has no return value. And cause this exception.

Apr 18 07:28:20 hassbian hass[8160]:     states = self._device.check_power()
Apr 18 07:28:20 hassbian hass[8160]:   File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 369, in check_power
Apr 18 07:28:20 hassbian hass[8160]:     data['s1'] = bool(state & 0x01)
Apr 18 07:28:20 hassbian hass[8160]: TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'#033[0m

**Comment by Danielhiversen** [comment]
Could you test this:
https://github.com/mjg59/python-broadlink/compare/master...bug_fix?quick_pull=1
