### ISSUE TITLE
Missing pycrypto dependency

### ISSUE THREAD

**Issue by technicalpickles** [mjg59/python-broadlink#24]
I had this library working on with a script one machine, and when moving to another, I got this error:
```
Traceback (most recent call last):
  File "send.py", line 3, in <module>
    import broadlink
  File "/home/pi/picklehome/lib/python3.5/site-packages/broadlink/__init__.py", line 4, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'
```

Found the fix as  `pip install pycrypto` on http://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher . That suggests to me it just needs to be a dependency.

**Comment by Danielhiversen** [comment]
@mjg59 Could you add pycrypto as a dependency?

**Comment by mjg59** [comment]
Fixed

**Comment by thomasf** [comment]
pycrypto is unmaintained and should not be used. https://github.com/Legrandin/pycryptodome should be used instead... On top of being unmaintained pycrypto doesn't install correctly on a bunch of platforms
