### ISSUE TITLE
must install cryptography, or it fail in silent.

### ISSUE THREAD

**Issue by optman** [mjg59/python-broadlink#253]
it should not fallback to pyaes, which won't work!  

https://github.com/mjg59/python-broadlink/blob/9d9b49c3db96a8e92c3b267aa07f764eff659e2b/broadlink/__init__.py#L14

**Comment by Danielhiversen** [comment]
Why does not pyaes work?

**Comment by optman** [comment]
I don't know,  i found response[0x22]  is not 0, which mean there is an error.  I have try it on different machines, there is only one works. I guess it must be enviroment issue. The one works,  there is no ```pyaes``` installed, but  ```cryptography``` is installed.  And i try to install ```cryptography``` on all other machines, all works. 

BTW, my device is sp2 mini.

**Comment by AnilDaoud** [comment]
same issue, i was not able to learn or send any command with only pyaes.
after i installed cryptography, it worked fine
device is rm mini3

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/281. Thank you!
