### ISSUE TITLE
wrong installation instruction for command line interface

### ISSUE THREAD

**Issue by PainElemental** [mjg59/python-broadlink#277]
The readme.md of the command line interface says in the section "Requirements", that you have to install "broadlink" using the command

> sudo pip install broadlink

On my Linux Mint I had to call

> sudo pip3 install broadlink

to get the command line interface working!

Maybe someone could correct the readme...

Regards
Bernd

edit:
Just found out that you need both, because broadlink_cli uses python3 and broadlink_discovery uses python2...

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/555. Thank you!
