### ISSUE TITLE
FreeBSD can't send 255.255.255.255

### ISSUE THREAD

**Issue by taniokaeiji** [mjg59/python-broadlink#306]
In my FreeBSD 12.1-STABLE on RaspberryPi 3B+, original python-broadlink can't discover my RMmini3.
Raspbian can discover.

FreeBSD default can't send packet to "255.255.255.255", limited broadcast.

PRed #303 .

**Comment by felipediel** [comment]
If you have multiple network interfaces, you need to specify a local_ip_address or send the message to the correct L3 broadcast address, eg. 192.168.0.255.
