### ISSUE TITLE
RM Mini 3 not discoverable or accepting auth if added using new Broadlink app

### ISSUE THREAD

**Issue by sebastian-silverwood** [mjg59/python-broadlink#307]
RM Mini 3 must be added/configured initially using either this library, or the older IHC or e-Control apps. If you set up the RM Mini using the newer Broadlink app, it will discover and connect fine, but never authenticate. This prevents learning and sending of commands.

This is true for any projects that use this library too (for me, it was the broadlink component in Home Assistant, and where my digging started).

I'm not very technical, so not sure if this is an issue with this library that can be patched, or if it's something to do with the Broadlink app itself. Just wanted to share my experience if people have more experience debugging.

**Comment by oTiMo** [comment]
thank you for this information. is it reversible?
I unfortunately used the newer application and I cannot use it

**Comment by trankillity** [comment]
Yes, it's reversible. Hold down the reset button on the back then set up using either python-broadlink CLI or ihc or eControl.

**Comment by oTiMo** [comment]
Thx, but it doesn't work. returned type is `0x5f36` it is really strange ...

````
Discovering...
###########################################
Unknown
# broadlink_cli --type 0x5f36 --host 192.168.1.21 --mac 5c4c7aa7df24

**Comment by creemerica** [comment]
Same here, device type is 0x5f36. Added it to the list for RM3 devices however not able to learn any commands.

**Comment by trankillity** [comment]
Strange! I'll admit that I set it up using the ihc app, which then allowed local auth/control (via Home Assistant's SmartIR addon, which uses python-broadlink).

**Comment by oTiMo** [comment]
> Same here, device type is 0x5f36. Added it to the list for RM3 devices however not able to learn any commands.

exactly the  same thing for me

**Comment by Nonobond007** [comment]
Hello I just bought an RM-Mini-3 on Amazon, broadlink_discovery returns me an rm device: 0x5f36.
I added this device to the init.py file, but it still doesn't work.

**Comment by oTiMo** [comment]
see #308

**Comment by dennisadvani** [comment]
I've received a few of the 0x5f36 type devices as well with firmware 44057. I can discover and configure them via python-broadlink but can't send any codes. Is anyone else able to send codes or is the issue you're experiencing only with learning them? Also, I initially configured via the new Broadlink app; after resetting and configuring via python, I still can't send codes.

**Comment by creemerica** [comment]
> I've received a few of the 0x5f36 type devices as well with firmware 44057. I can discover and configure them via python-broadlink but can't send any codes. Is anyone else able to send codes or is the issue you're experiencing only with learning them? Also, I initially configured via the new Broadlink app; after resetting and configuring via python, I still can't send codes.

Nope same thing here, I opened #308 regarding this same exact issue. Haven't been able to get it to learn new codes.

**Comment by felipediel** [comment]
Fixed by #317.

**Comment by felipediel** [comment]
This is a feature of the firmware of these new devices. Once connected to the cloud, they block local authentication. You need to [disable the cloud](https://github.com/home-assistant/core/issues/30215#issuecomment-581159499) in order to control them locally. There is nothing that can be done about it at library level.

**Comment by felipediel** [comment]
When the device is locked - this is done automatically after authentication in the Broadlink app - it does not authenticate external applications, including this one. Now there is a button to unlock the device in the Broadlink app. This issue no longer exists. Closing.
