### ISSUE TITLE
RM Mini 3 (0x5f36) Does Not Learn Codes

### ISSUE THREAD

**Issue by creemerica** [mjg59/python-broadlink#308]
I purchased 2 RM Mini 3s off of Amazon and they both register as 0x5f36, however even after adding them to the rm list they do not learn any codes. I was able to enter learning mode however none of the codes are printed to the terminal window.

I am able to add/learn codes in the various apps but not through this library. Any idea why or does anyone have this specific device and got it working?

**Comment by Nonobond007** [comment]
217/5000
Hello I just bought an RM-Mini-3 also on Amazon, broadlink_discovery returns me an rm device: 0x5f36.
I added this device to the __init__.py file, but it still doesn't work.
How can I do?

Thank you so much.

**Comment by Siytek** [comment]
> I purchased 2 RM Mini 3s off of Amazon and they both register as 0x5f36, however even after adding them to the rm list they do not learn any codes. I was able to enter learning mode however none of the codes are printed to the terminal window.
> 
> I am able to add/learn codes in the various apps but not through this library. Any idea why or does anyone have this specific device and got it working?

Exactly the same for me, I just purchased two from eBay, device ID 0x5f36, can setup and discover but learning does not work. Has anyone looked inside these newer units?

**Comment by Cioriz** [comment]
I'm having this issue as well in 2, just bought, RM Mini 3 devices (amazon.it and ebay.it).

`Discovering...
###########################################
Unknown
# broadlink_cli --type 0x5f36 --host  --mac
Device file data (to be used with --device @filename in broadlink_cli) : 
0x5f36`

Please dear skilled developers help us out, i can't really miss the local polling on this device!!

**Comment by elafargue** [comment]
Are the reports above all for the red version of the RM3, or do some people experience this with the black version as well?

**Comment by Siytek** [comment]
> Are the reports above all for the red version of the RM3, or do some people experience this with the black version as well?

Mine's the black version

**Comment by martinrehfeld** [comment]
Crosslinking https://github.com/home-assistant/home-assistant/issues/30215 as some active investigation on said device is going on over there.

**Comment by umarbutler** [comment]
Hi, any updates on a solution for this issue? I have the same firmware (v44057) and have been unable to connect my RM Mini 3 to HA as well as Broadlink Manager (keep getting the error 'Writing compatible device not detected!'). I have tried configuring the device to connect to Wi-Fi via both the IHC and Broadlink apps (using both AP and Bluetooth modes), to no avail.

**Comment by felipediel** [comment]
Fixed by #317.

**Comment by Snocksman** [comment]
Hi ! I´m using FHEM and have a Problem with one of the 0x5f36 RM3 mini Devices. The FHEM Module depends on this python script, but the fix for the new RM mini 3 Devices has not been implemented. Could you maybe have a look at the FHEM Module, maybe it´s only little work for you to fix this Module... You can send me a mail if i should send you the Module File: snocksman@t-online.de

**Comment by felipediel** [comment]
Fixed with #317. Thank you!
