### ISSUE TITLE
RM Mini 3 Blackbean

### ISSUE THREAD

**Issue by noddy119** [mjg59/python-broadlink#31]
Over on the Domiticz forums (https://www.domoticz.com/forum/viewtopic.php?f=17&t=6929&start=100#p103517) we have been using your library to integrate broadlink.  I have a RM Mini 3 Black Bean and need to use 'broadlink.device' where the RM pro needs 'broadlink.rm'.  I supect the RM Mini 3 was released after you wrote your excellent library?

Is there a way I can supply you with the devicetype hex so you can midify the library so the same code can be used?

Secondly; can I use your code to return the mac address following a device discovery?  I worked out how to return the ip address.  This would save having to look at the router etc.

**Comment by mjg59** [comment]
Yes, please just send the devtype that's passed to gendevice() and I'll add it.

**Comment by noddy119** [comment]
How would I do that?

**Comment by JayPearlman** [comment]
@noddy119 You can modify the code to print out the "devtype" in the middle of the discover call. You would add a new line 111 - "print devtype". Then a recompile/install of the module.

My mini 3 black bean returns 10039 or 0x2737 in hex, which is already in the code and is seemingly properly handled by the discover function. 

I think some confusion may be coming from the scripts over at domoticz.com which are skipping the discover function and creating the device in a more manual way.

Hope this helps.

**Comment by noddy119** [comment]
Hi Jay - I was using an old module version - doh!  Yes my mini 3 black bean returns 10039.  With the module updated I can use 'broadlink.rm' instead of 'broadlink.device'
