### ISSUE TITLE
Usage impossible - PyCRC is now a different package

### ISSUE THREAD

**Issue by majuss** [mjg59/python-broadlink#311]
The original PyCRC (http://pydoc.net/PyCRC/1.21/PyCRC.CRC16/) is not longer available on pypi and was replaced by: https://github.com/tpircher/pycrc.

So currently this software is not usable at all :(

The original package can be found here: https://mega.nz/#!30AkwQyB!6_bu-9gM9TcxgTANeeTI_m2rVAOIIMT_Rg3RgJZ1si4

**Comment by hazbot72** [comment]
I ran into this same issue while installing on Raspberry PI 4, but was able to work around it by installing an archived copy of PyCRC 1.21 from piwheels:

https://www.piwheels.org/project/PyCRC/

**Comment by tlc76** [comment]
I ran into the same issue...
How did you install the file PyCRC-1.21.zip ?
I cannot find any setup.py inside...

Thanks!

**Comment by tlc76** [comment]
I managed to install the PyCRC-1.21-py2.py3-none-any.whl file.
All working fine now, thanks!

**Comment by majuss** [comment]
We should remove this dependency, otherwise this lib will die!

**Comment by majuss** [comment]
https://github.com/mjg59/python-broadlink/pull/327

PR is open :=
