### ISSUE TITLE
Homebridge Comparability with RMI4 Mini

### ISSUE THREAD

**Issue by adham-ibrahim20** [mjg59/python-broadlink#312]
Hi,,,

I have serious problem with RM4 mini , which is not compatible with Homebridge,, so i need to know it their is any update to solve this issue,

-----We've discovered an unknown Broadlink device. This likely won't cause any issues.
Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "4e97". The device is connected to your network with the IP address "192.168.1.6".

* also when i scan it using Broadlink manager it appeared that it's unknown device.

**Comment by felipediel** [comment]
I think this device can be controlled with our rm4 class. In the rm4 class, you need to prefix the payload with its length.
## Before
```python3
b'\x03\x00\x00\x00'
```
## After
```python3
b'\x04\x00\x03\x00\x00\x00'
```
If you want I can help to add support here. Homebridge is another module, I don't have access to their code base.
