### ISSUE TITLE
Next release ETA? 

### ISSUE THREAD

**Issue by b4dpxl** [mjg59/python-broadlink#316]
Hi. Thanks for this project :) I've extended the Home Assistant component to support the BG1 devices now that those are supported by this library, but as HA uses pip to load components this can't be fully integrated? I wondered if there was an ETA as to when the next version with the BG1 support would be released to pip?

Thanks

**Comment by Danielhiversen** [comment]
0.13.0 is now released

**Comment by b4dpxl** [comment]
thank you :)
