### ISSUE TITLE
don't work with spmini3 type 0x7d11

### ISSUE THREAD

**Issue by netsun-github** [mjg59/python-broadlink#318]
don't work with spmini3 type 0x7d11

**Comment by nhadnt** [comment]
I need help with spmini3 type 0x7d11! (how to connected from hass. Thanks)

**Comment by felipediel** [comment]
Hello. Has this problem been resolved?

**Comment by felipediel** [comment]
We've already added support for this device, so I assume that this issue no longer exists. If it is still not working, please reopen it.
