### ISSUE TITLE
Paranoid question - will RM3 mini communicate with any internet server if used through this python API?

### ISSUE THREAD

**Issue by flagg19** [mjg59/python-broadlink#334]
I'm a little paranoid and I don't want my RM3 mini to connect to any internet server. I've read that using it the normal way through the official app it does, but it's not clear to me if the same applies to this python API.

Should I put it on an WiFi with no internet access? Would it even work that way?
Thanks.

**Comment by Danielhiversen** [comment]
The api is local, but the device is still connected to the Internet.
You could try to block internet access for your device
