### ISSUE TITLE
  File "BlackBeanControl.py", line 168, in <module>     RM3Device.auth()   File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 211, in auth     response = self.send_packet(0x65, payload)   File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 261, in send_packet     checksum = adler32(payload, 0xbeaf) & 0xffff TypeError: adler32() argument 1 must be string or read-only buffer, not bytearray

### ISSUE THREAD

**Issue by marcol79** [mjg59/python-broadlink#349]
File "BlackBeanControl.py", line 168, in <module>
    RM3Device.auth()
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 211, in auth
    response = self.send_packet(0x65, payload)
  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 261, in send_packet
    checksum = adler32(payload, 0xbeaf) & 0xffff
TypeError: adler32() argument 1 must be string or read-only buffer, not bytearray

Any idea?

**Comment by Danielhiversen** [comment]
Use the latest version of library.
(And should use puthon 3)

**Comment by marcol79** [comment]
python3 BlackBeanControl.py -c COND_ON
  File "BlackBeanControl.py", line 197
    if (len(SentCommand) <> 8) or (not all(c in string.hexdigits for c in SentCommand)):

**Comment by marcol79** [comment]
sorry but i'm not a programmer
