### ISSUE TITLE
HTS2 sensor

### ISSUE THREAD

**Issue by sagitt** [mjg59/python-broadlink#351]
Hi, i don't know if this is the correct section

new rm4 support this cable with umidity\temperature sensor.

you think is possible integrate it?

https://www.amazon.it/gp/product/B081GDH5TM/ref=ox_sc_act_title_1?smid=A39FSSU0WTOOK8&psc=1

**Comment by hakana** [comment]
It works with RM4 mini, don't know if the same for RM4.

**Comment by felipediel** [comment]
@sagitt Do you have the HTS2 cable? Would you mind helping me test [these changes](https://github.com/mjg59/python-broadlink/pull/374)?

**Comment by sagitt** [comment]
> @sagitt Do you have the HTS2 cable? Would you mind helping me test [these changes](https://github.com/mjg59/python-broadlink/pull/374)?

Yes, with rm4 pro

**Comment by felipediel** [comment]
@sagitt Thank you!

**Comment by sagitt** [comment]
> @sagitt Thank you!

Tell me how test new version

**Comment by felipediel** [comment]
I thought you had already tested :smile:
I just made a custom [debug script](https://drive.google.com/file/d/1EWntL_m3oY4gHqoan9DQo1RRXnv6vq2m/view?usp=sharing) to make your life easier. Run it on your computer with:

`python3 debug-sensor.py`

Then send me debug.txt.

**Comment by sagitt** [comment]
> I thought you had already tested 😄
> I just made a custom [debug script](https://drive.google.com/file/d/1EWntL_m3oY4gHqoan9DQo1RRXnv6vq2m/view?usp=sharing) to make your life easier. Run it on your computer with:
> 
> `python3 debug-sensor.py`
> 
> Then send me debug.txt.

So only need broadlink with cable on my netwoek, right!? Tomorrow i’ll do it.

**Comment by felipediel** [comment]
Yes.

**Comment by felipediel** [comment]
You no longer need to test. The code is working. But thanks anyway.

**Comment by sagitt** [comment]
> You no longer need to test. The code is working. But thanks anyway.

I’m happy!

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/321. Thank you!
