### ISSUE TITLE
cli-discovery argument typo

### ISSUE THREAD

**Issue by fusenuk** [mjg59/python-broadlink#357]
https://github.com/mjg59/python-broadlink/blob/5e444988e1d41427171273241c6a88955fbf1601/cli/broadlink_discovery#L10

https://github.com/mjg59/python-broadlink/blob/5e444988e1d41427171273241c6a88955fbf1601/cli/broadlink_discovery#L14

Line 10 adds the new argument `dst-ip` and then line 14 references `dst_ip` which causing an error that an unknown argument has been detected.

**Comment by ameer1234567890** [comment]
The fix could be #361

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/361. Thank you!
