### ISSUE TITLE
RM Pro + causes exception on sweep_frequency()

### ISSUE THREAD

**Issue by KhArtNJava** [mjg59/python-broadlink#366]
I just downloaded these scripts and trying to understand, how use it with Broadlink RM Pro+ (BROADLINK_RM_3322_2).

Now my Python script is:
```
import broadlink
devices = broadlink.discover(timeout=5)
print(devices)
devices[0].auth()
devices[0].enter_learning()
devices[0].sweep_frequency()
```
This script causes exception 

c:\Python_3.7>python br.py
[<broadlink.rm object at 0x000001CEF5EBFE08>]
Traceback (most recent call last):
  File "br.py", line 11, in <module>
    devices[0].sweep_frequency()
  File "c:\Python_3.7\lib\site-packages\broadlink\__init__.py", line 621, in sweep_frequency
    check_error(response[0x22:0x24])
  File "c:\Python_3.7\lib\site-packages\broadlink\exceptions.py", line 97, in check_error
    raise exception(error_code)
broadlink.exceptions.UnknownError: Unknown error: 0xc

P. S. I've already successfully sent 
```
import broadlink
broadlink.setup('Art', '********', 3)
```
Broadlink RM Pro+ configured and connected to Art Wi-Fi and 
`devices = broadlink.discover(timeout=5)` founds it.

File with packages from WireShark is attached to this issue.
[broadlinkSweep.zip](https://github.com/mjg59/python-broadlink/files/4611570/broadlinkSweep.zip)

How to fix this issue?

**Comment by GF-Huang** [comment]
@KhArtNJava Hey guys how did you fix it?

![image](https://user-images.githubusercontent.com/4510984/104393318-23841b80-557f-11eb-80c4-fe96ad5b015b.png)

**Comment by KTibow** [comment]
@GF-Huang just some pre-steps: install the latest version of python (3.9) and python-broadlink (0.16.0).

**Comment by GF-Huang** [comment]
> @GF-Huang just some pre-steps: install the latest version of python (3.9) and python-broadlink (0.16.0).

Why not python 3.7?

**Comment by KTibow** [comment]
Just in case. Also check the dependencies.

**Comment by GF-Huang** [comment]
I'm using the latest version of python-broadlink.

![image](https://user-images.githubusercontent.com/4510984/104393863-6db9cc80-5580-11eb-9211-131f5ead7f5c.png)

**Comment by GF-Huang** [comment]
And my device is RM Pro Plus
