### ISSUE TITLE
Anyway to make the TC2 switch work with RM4 Pro ?

### ISSUE THREAD

**Issue by com-xuonghuynh** [mjg59/python-broadlink#373]
Hi, I have 2 TC2 switch and a RM4 Pro. All working fine with broadlink app, but I don't know how to get the RF code and control the TC2 via my home assistant. I have try all method that I can find on internet such as e-control app (this not support for RM new devices), buy external remove (can learn code from other remote but can not learn when send on off switch) .

**Comment by felipediel** [comment]
Now you can learn RF commands with Home Assistant. Closing.
