### ISSUE TITLE
Modifying "repeat count" in learned IR HEX.

### ISSUE THREAD

**Issue by jameswberry** [mjg59/python-broadlink#376]
Is it possible to modify the "repeat count" of a learned HEX code when sending?

I see in the protocol documentation for [sending data](https://github.com/mjg59/python-broadlink/blob/master/protocol.md#sending-data) that the protocol supports the "repeat count" value, but it's not clear how one would modify the HEX code from the learn command.

Ideally, this would be a supported function similar to --convert and --durations. I think I'm close with the following steps but it's not quite working.

```
broadlink_cli --type 0x62bc --host x.x.x.x --mac xxxxxxxxxxxx --learn

260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000
```

**Comment by felipediel** [comment]
If you want to manipulate the repeat count, you need to convert the hex to bytes first. You can use this:
```python3
>>> b = bytes.fromhex('260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000260050000001269513121237133614361312123714361337123613371237131212131313121213371238123713111412121412131113131313361312121313121214111312131213120005950001264a13000d050000000000000000')
>>> b[1] = 255  # Number of repetitions
```
Closing.
