### ISSUE TITLE
S1 support

### ISSUE THREAD

**Issue by radinsky** [mjg59/python-broadlink#39]
Hey

Is there any chance to add support for S1 SmartOne Security Kit?
To get its sensor statuses and etc?

Thanks

![image](https://cloud.githubusercontent.com/assets/4540268/21454976/8130d178-c925-11e6-87bc-8da62987b6ad.png)

**Comment by radinsky** [comment]
possible duplicate request from https://github.com/mjg59/python-broadlink/issues/18

**Comment by mjg59** [comment]
Yup, dupe of #18 - closing to keep that one open.
