### ISSUE TITLE
broadlink_cli requires python3

### ISSUE THREAD

**Issue by marc-invalid** [mjg59/python-broadlink#398]
broadlink_cli requires python3 since commit 4e33ef44 which also introduced the ```--rfscanlearn``` option.  However, the script works fine on python2, with exception of the ```input()``` call which needs attention.

RF learning works fine on python2 after fixing this issue and also issue #397 (tested with RM4 Pro on CentOS7).

Please consider accepting this patch to undo the requirement.

```
diff --git a/cli/broadlink_cli b/cli/broadlink_cli
index a2e1883..3cec07b 100755
--- a/cli/broadlink_cli
+++ b/cli/broadlink_cli
@@ -1,4 +1,4 @@
-#!/usr/bin/env python3
+#!/usr/bin/env python
 
 import argparse
 import base64
@@ -213,7 +213,10 @@ if args.rfscanlearn:
     print("Found RF Frequency - 1 of 2!")
     print("You can now let go of the button")
 
-    input("Press enter to continue...")
+    try:
+        raw_input("Press enter to continue...")
+    except NameError:
+        input("Press enter to continue...")
 
     print("To complete learning, single press the button you want to learn")

```

**Comment by felipediel** [comment]
Sorry, we no longer support Python 2. Closing.
