### ISSUE TITLE
RM2 does not send anything

### ISSUE THREAD

**Issue by salmorejos** [mjg59/python-broadlink#399]
RM2 does not send anything
When updating the version of broadlink python now I can't get RM2 to send any code (which previously worked with another older version of broadlink python).
I leave you a screenshot of the file I am trying to run and the error I receive.
Any suggestion of what happens to the code, where
 can I be making the mistake? .... THANK YOU.
![enviarcodigo](https://user-images.githubusercontent.com/67859387/88464754-96a8b100-cebd-11ea-9064-df087d5e2671.jpg)

![enviarcodigoerror](https://user-images.githubusercontent.com/67859387/88464761-a0caaf80-cebd-11ea-979d-52cb7f5b2186.jpg)

**Comment by felipediel** [comment]
Probably an indexing error because Python 2 treats bytes differently. Sorry, we no longer support Python 2. Closing.

**Comment by KTibow** [comment]
@felipediel maybe you should add a label to issues as for why they were closed?
