### ISSUE TITLE
Cannot send command

### ISSUE THREAD

**Issue by 22mSqRi** [mjg59/python-broadlink#400]
Hi, I tried send command to eRemote mini(RM Mini 3 for Japan), but error has occurred.
What should I do?

devices: raspberry pie zero WH + Python 2.7.16,  eRemote mini(RM Mini 3 for Japan)

log:
>import broadlink
　　→devices = broadlink.discover(timeout=5)
print(devices)
　　→[<broadlink.rm instance at (device code)>]
devices[0].auth()
　　→True
> devices[0].enter_learning()
> ir_packet = devices[0].check_data()
> print(ir_packet)
　　→(command code)
> devices[0].send_data(ir_packet)
　　→**Traceback (most recent call last):
　　  File "<stdin>", line 1, in <module>
　　  File "/usr/local/lib/python2.7/dist-packages/broadlink/__init__.py", line 609, in send_data
 　　   check_error(response[0x22:0x24])
　　  File "/usr/local/lib/python2.7/dist-packages/broadlink/exceptions.py", line 97, in check_error
　　    raise exception(error_code)
　　  broadlink.exceptions.CommandNotSupportedError: Command not supported**

**Comment by felipediel** [comment]
Sorry, we no longer support Python 2.
