### ISSUE TITLE
Control/Setup Wemo Bulbs with Broadlink Pro

### ISSUE THREAD

**Issue by xSeekTruthx** [mjg59/python-broadlink#405]
Currently have broadlink pro, works great with your code, thank you. 

I see you have Wemo emulation in other projects. Is it possible (without any other Wemo hardware) to control/setup a Wemo Bulb with my existing broadlink pro hardware?

**Comment by KTibow** [comment]
What exactly do you mean? This isn't a question related to Python.

**Comment by felipediel** [comment]
Wemo bulbs communicate via Wi-Fi and ZigBee. RM pros are only able to send IR and RF codes. So the answer is no, sorry.
