### ISSUE TITLE
sweep_frequency() crashes RM mini 3

### ISSUE THREAD

**Issue by intriguedlife** [mjg59/python-broadlink#409]
Just as the title of this problem says: sweep_frequency() crashes my RM mini 3. I get the message broadlink.exceptions.DeviceOfflineError: The device is offline.

The RM mini 3 won't respond to any other command afterwards. Other commands will only work again when I restart the device by removing power.

My RM mini 3 is model 0x5f36: (rm4, "RM mini 3", "Broadlink") and has firmware version 44057.
I can capture packets that are sent to the device if needed.

Can someone assist me with this problem?

**Comment by felipediel** [comment]
RM mini 3 does not support sweep_frequency().

**Comment by intriguedlife** [comment]
Ok. Thanks for the reply.

Should this be mentioned in the readme?

**Comment by steffenu** [comment]
The readme could use abit of clarification and additonal info / examples

**Comment by felipediel** [comment]
We need to add some kind of "support_rf" flag in the future, I will do it. For now this method needs to be used consciously.

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/529. Thank you!
