### ISSUE TITLE
i has 1 sp,mini.but check_power is error

### ISSUE THREAD

**Issue by dajiavip** [mjg59/python-broadlink#44]
https://gyazo.com/0478c5401556390fbfdb503504aa10c6

**Comment by mjg59** [comment]
Can you change check_power() to include

print(payload,)

just above the return bool(payload[0x4]) line in check_power? Include the comma after payload. Then perform the same test you did in the screenshot and let me know what output you get for the two check_power() calls?

**Comment by eddyyanto** [comment]
Same issue #51 I think?

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/72. Thank you!
