### ISSUE TITLE
Broadlink RM mini 3 (0x27c7) Not working

### ISSUE THREAD

**Issue by wong8369** [mjg59/python-broadlink#441]
system info:
```
arch | armv7
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 5.4.51-v7+
python_version | 3.7.3
version | 0.115.6
virtualenv | true
```

error log:
`2020-10-07 22:07:28 ERROR (MainThread) [homeassistant.components.broadlink] Unsupported device: 0x27c7. If it worked before, please open an issue at https://github.com/home-assistant/core/issues`

**Comment by felipediel** [comment]
Thank you! Is this an OEM? (manufactured by Broadlink and distributed by another brand)
I cannot find it in any official app.
