### ISSUE TITLE
Broadlink device unlock

### ISSUE THREAD

**Issue by astra1** [mjg59/python-broadlink#449]
I think broadlink heard my feature request and officially added unlock device toggle in version 1.5.03. Now unlocking will be simpler :)

device: RM4Pro

![image](https://user-images.githubusercontent.com/4422785/95654720-9c9c4e80-0b0a-11eb-98d3-b4292af847b4.png)

**Comment by Beendiis** [comment]
I have version 1.5.10 and i can't find "lock device " :(  Maybe is only on your version ?

**Comment by KTibow** [comment]
Nope, I have it too. What kind of device do you have?

**Comment by Beendiis** [comment]
RM4 pro. On which menu is "device info" , "Firmware update", .....,

**Comment by KTibow** [comment]
@Beendiis I have a SP4-US, and it shows up. Anyway wrong place, create a new issue, and @astra1 you might want to consider closing this issue so it doesn't have 
![image](https://user-images.githubusercontent.com/10727862/97806584-2f637100-1c11-11eb-97bc-38278121bac2.png)
issues.

**Comment by CyborgVette** [comment]
I found the unlock toggle but it still doesn't really unlock. The Home Assistant and the Hubitat won't connect. Do I use the AP mode or the Smart mode install?
