### ISSUE TITLE
understanding ir packet

### ISSUE THREAD

**Issue by alonizyl** [mjg59/python-broadlink#450]
hi, im trying to use the remote as a trigger in my code, every time i press the button i get different results is there and way to decrypt the ir packet and know if it the same button?

![Screenshot_1](https://user-images.githubusercontent.com/17926043/95656997-d51a3900-0ac6-11eb-8eb1-8437e0d0f167.png)

**Comment by alonizyl** [comment]
> hi, im trying to use the remote as a trigger in my code, every time i press the button i get different results is there and way to decrypt the ir packet and know if it the same button?
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/17926043/95656997-d51a3900-0ac6-11eb-8eb1-8437e0d0f167.png)

**Comment by felipediel** [comment]
Hi. This is normal. Some codes have a toggle bit, so the device is able to differentiate a short press from a long press for example. The codes are not encrypted in the image you sent, they are in raw byte format. If you want to understand how this works you can read the [protocol](https://github.com/mjg59/python-broadlink/blob/master/protocol.md).

Not something to be fixed. Closing.
