### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KTibow** [mjg59/python-broadlink#457]
It's been almost a month since the last release, and a lot has been added since. I think it's time for @mjg59 to create a new release.

**Comment by mjg59** [comment]
@felipediel Is everything you want in at this point?

**Comment by felipediel** [comment]
I'm working on a last update. Then I think we'll be ok for a release. Thank you @mjg59!

**Comment by mjg59** [comment]
Perfect, let me know!

**Comment by thiagogsr** [comment]
hey @felipediel @mjg59 any plans to a new release? I would like to use a device that was added after the latest release.

**Comment by felipediel** [comment]
I just released v0.17.0. Closing.
