### ISSUE TITLE
Is it possible to transmit IR byte array without going through learning process

### ISSUE THREAD

**Issue by narongdejsrn** [mjg59/python-broadlink#48]
For example I want to transmit a byte array 

[0x52, 0xAE, 0xC3, 0x1A, 0xE5, 0x90, 0x00, 0xF0, 0x00, 0xF0, 0x00, 0x0D, 0x00, 0x10, 0x00, 0xFF, 0x00, 0x7B, 0x00] 

Can I do that without going through learning process?

**Comment by sirl1on** [comment]
have you tried? Can't test it but it should work, have sent payloads loaded from file successfully

````
import broadlink
devices = broadlink.discover(timeout=5)
devices[0].auth()
payload = bytearray([0x52, 0xAE, 0xC3, 0x1A, 0xE5, 0x90, 0x00, 0xF0, 0x00, 0xF0, 0x00, 0x0D, 0x00, 0x10, 0x00, 0xFF, 0x00, 0x7B, 0x00])
devices[0].send_data(payload)
````

**Comment by felipediel** [comment]
Yes.
