### ISSUE TITLE
RM mini 3 doesn't get discovered

### ISSUE THREAD

**Issue by Rania-M** [mjg59/python-broadlink#484]
Hi,
i'm trying to control an RM mini 3 device via the broadlink api, the device is easily recognized by the mobile app, but folowing the readme steps doesn't get it discovered on the api.
**Steps** : reset the device , set the wifi in the api, launch the discover
**Result** : it returns an empty list

_PS_: i did turn off the device lock on the mobile app
Thank you

**Comment by KTibow** [comment]
Don't use the mobile app at all.

**Comment by Rania-M** [comment]
> Don't use the mobile app at all.

Thank you for your response,
I didnt usé the mobile app at first and it wasn't working (always empty list)

**Comment by KTibow** [comment]
If you install Fing on your phone, and connect it to the same network as your PC, can you find the device?

**Comment by KTibow** [comment]
Never mind, it hasn't been merged yet: https://github.com/mjg59/python-broadlink/pull/479

**Comment by Rania-M** [comment]
> Never mind, it hasn't been merged yet: #479

thank you, so the device is not supported yet ?

**Comment by felipediel** [comment]
@Rania-M If you have multiple network interfaces (eg WiFi, Ethernet), you can try to reach the device by specifying a local_ip_address or discover_ip_address in discover().

**Comment by Rania-M** [comment]
> @Rania-M If you have multiple network interfaces (eg WiFi, Ethernet), you can try to reach the device by specifying a local_ip_address or discover_ip_address in discover(). If you don't give these arguments, the OS will bind the socket to the first available interface and the message may end up being transmitted to the wrong network. You can also try direct discovery:
> 
> ```python
> device = broadlink.hello("192.168.0.12")  # Example IP address
> ```

Thank you ! i did this but still didn't work, i, however, changed the computer as i was only tring with a virtual machine first, and now it's working :+1: 
I can now detect the RM mini 3, the only problem is that it is assigned to the RM4 class, and it seems ans i can't find a way to send data to the device ( o function found there)
I can try to use the RM fsend data function , but i was wondering why this has not been impelmented.
Thank you in advance !

**Comment by felipediel** [comment]
Some devices use the RM4 class (eg RM mini 3 0x5f36). This class has the same interface of RM2 and all the methods are implemented.

**Comment by Rania-M** [comment]
> Some devices use the RM4 class (eg RM mini 3 0x5f36). This class has the same interface of RM2 and all the methods are implemented.

Thank you, i finally used the cli files, i will close thi subjectif if no objections 
Thanks to all 😊
