### ISSUE TITLE
One of my remote controllers can't be detected

### ISSUE THREAD

**Issue by fsalum** [mjg59/python-broadlink#496]
Hi,

I successfully learned 3 RF remote controls but I'm having some problems to learn my awning remote control on 433.42 Mhz frequency. Via the broadlink mobile app it detects without any issue, but using the cli I don't get anything, tried multiple times.

```bash
$ ./broadlink_cli.py --type 0x649b --host 192.168.1.114 --mac a043b0190e7f --rfscanlearn
Learning RF Frequency, press and hold the button to learn...
RF Frequency not found
```

Any idea what could be happening ?

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/518.
