### ISSUE TITLE
SCB1E (0x5115)

### ISSUE THREAD

**Issue by RenierM26** [mjg59/python-broadlink#512]
Hi There,

Could you please add support for scb1e with code 0x5115?

It's a broadlink bestcon power metering wifi switch with 16a max current.

I'm more than willing to test or provide any info required.

Thank you for all the work on this api!

**Comment by RenierM26** [comment]
#514

**Comment by RenierM26** [comment]
After adding

0x5115: (sp4b, "SCB1E", "Broadlink"),

to __init__.py

C:\Users\renier\AppData\Roaming\Python\Python39\site-packages\broadlink>python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import broadlink as blk
>>> dev=blk.hello("192.168.1.238")
>>> dev.auth()
True
>>> dev.get_state()
{'pwr': 1, 'indicator': 1, 'maxworktime': 0, 'current': 0.0, 'volt': 230.6, 'power': 0.0, 'totalconsum': 265.37, 'overload': 0.0}
>>> dev.get_state()
{'pwr': 1, 'indicator': 1, 'maxworktime': 0, 'current': 0.0, 'volt': 230.6, 'power': 0.0, 'totalconsum': 265.37, 'overload': 0.0}
>>> dev.get_state()
{'pwr': 1, 'indicator': 1, 'maxworktime': 0, 'current': 0.0, 'volt': 230.6, 'power': 0.0, 'totalconsum': 265.37, 'overload': 0.0}
>>> dev.get_state()
{'pwr': 1, 'indicator': 1, 'maxworktime': 0, 'current': 0.0, 'volt': 230.6, 'power': 0.0, 'totalconsum': 265.37, 'overload': 0.0}
>>> dev.get_state()
{'pwr': 1, 'indicator': 1, 'maxworktime': 0, 'current': 0.0, 'volt': 230.7, 'power': 0.0, 'totalconsum': 265.37, 'overload': 0.0}
>>> dev
<sp4b: Broadlink SCB1E (0x5115) at 192.168.1.238:80 | c8:f7:42:f8:d8:a6 | SCB1E | Unlocked>
>>>

**Comment by RenierM26** [comment]
100%

**Comment by KTibow** [comment]
Could this be closed then?

**Comment by RenierM26** [comment]
Hi there, 

Resolved. Thank you!
