### ISSUE TITLE
Ability to learn RF codes by providing frequency and not sweeping frequency

### ISSUE THREAD

**Issue by b-per** [mjg59/python-broadlink#539]
Hi,

I am trying to learn commands from a fan RF remote using an RM4 Pro. Using the Broadlink app (1.6.11), I can get the scan/sweep the frequency used (433.93 MHz in my case) and then learn commands in the mobile app without having to scan frequencies again, just inputting the frequency value I got before.

While using broadlink_cli though, I can't seem to pass the frequency scan step. I have tried to press on all the buttons of the remote but always get "RF Frequency not found". Would it be possible to provide the exact frequency required for learning RF codes, without scanning?

**Comment by DarkStarSword** [comment]
See my pull request: https://github.com/mjg59/python-broadlink/pull/613
