### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by supagu** [mjg59/python-broadlink#544]
I checked out the git repo from here: https://github.com/mjg59/python-broadlink

then tried to run broadlink_discovery

but i get the following error:

[s@server cli]$ ./broadlink_discovery 
Discovering...
Traceback (most recent call last):
  File "/home/s/Projects/python-broadlink/cli/./broadlink_discovery", line 16, in <module>
    if device.auth():
  File "/usr/lib/python3.9/site-packages/broadlink/device.py", line 198, in auth
    check_error(response[0x22:0x24])
  File "/usr/lib/python3.9/site-packages/broadlink/exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: [Errno -1] Authentication failed
[s@server cli]$ 

What does this mean and how to I get around the problem?

**Comment by supagu** [comment]
I found this thread:
https://github.com/mjg59/python-broadlink/issues/501

I needed to go into the broadlink app and unlcok the device. This has fixed it.

**Comment by pinei** [comment]
> I found this thread:
> #501
> 
> I needed to go into the broadlink app and unlcok the device. This has fixed it.

How did you get this broadlink app?

**Comment by KTibow** [comment]
From the Google Play store.
