### ISSUE TITLE
problem after home assistant update

### ISSUE THREAD

**Issue by smogalia** [mjg59/python-broadlink#547]
after every update, i must repeat all the step to make my rm4 pro /rm4 mini and my rm4c working...

**Comment by kylemd** [comment]
Correct. As the instructions listed through a number of posts here is unofficial Home Assistant will overwrite the install on every update.

Once 17.0 is pushed to PyPi (which should be soon) this will no longer be a problem and you can install from Home Assistant without any command line nonsense.

**Comment by KTibow** [comment]
Consider closing? This is an issue with a fix incoming.

**Comment by felipediel** [comment]
You need to wait until the code reaches the end of the line.
