### ISSUE TITLE
Broadlink LB1 0x60c8 unable to authenticate

### ISSUE THREAD

**Issue by goncalovalverde** [mjg59/python-broadlink#571]
Hi.

I've been trying to use this module with a Broadlink LB1 0x60c8 bulb but I'm getting an error while trying to authenticate.
This is the response that I'm getting when I do a device.auth:
'Z\xa5\xaaUZ\xa5\xaaU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00;\xcc\xff\xff\xc8`\xe9\x03 \xa1\xd0;\xb2\xb0C\xa0\x00\x00\x00\x00\xaf\xbe\x00\x00'

This fails on the check_response

Any pointers?

**Comment by KTibow** [comment]
Could you please format your data using backticks instead of quotes? @felipediel do you know anything about this?

**Comment by felipediel** [comment]
The device is locked. You need to unlock the device in the official app.

**Comment by goncalovalverde** [comment]
I had the bulb configured using the magic home - smart home app which is the one recommended on the box of the bulb.
The info from doing a discover stated that the bulb was unlocked
Anyway I downloaded the broadlink app and after reseting the bulb I managed to send the wifi configuration. 
The broadlink app complained about the region and the lamp doesn't appear in the application. 
Nevertheless this seems to have done the trick to unlock the lamp and now I can authenticate and control the lamp via python.
Thank you for your feedback

**Comment by felipediel** [comment]
You're welcome!

**Comment by felipediel** [comment]
@goncalovalverde I know the issue is resolved, but do you mind helping me understand why the lock status is incorrect?

```python3
import socket

with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as conn:
	packet = bytearray(0x30)
	packet[0x26] = 6
	conn.sendto(packet, ('192.168.0.16', 80))  # Example LB1 IP address
	conn.settimeout(5)
	print(conn.recvfrom(2048))
```
What is the output?

**Comment by goncalovalverde** [comment]
Sure.
Here goes the output:

(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>\xcc\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc7`\x94\x01\xa8\xc0\xc3jL\xb0C\xa0Smart Bulb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x01E\x9a\x9aE\x02\x00\x00\x00xs\x1dF\x8f\x0c\x00\x00\x00\x00', ('192.168.1.148', 80))

**Comment by felipediel** [comment]
Thank you!
