### ISSUE TITLE
LB1 Model Authentication error 

### ISSUE THREAD

**Issue by mukhopadhyaypinaki** [mjg59/python-broadlink#574]
I am using below command to connect to my bulb.
Using your subnet's broadcast address with discover_ip_address

import broadlink

devices = broadlink.discover(timeout=5, discover_ip_address='192.168.0.255')

the output is as below
 devices = broadlink.discover(timeout=5, discover_ip_address='192.168.0.255')
>>> devices[0]
broadlink.light.lb1(('192.168.0.XX', 80), mac=<XXXXXXXXXXXXXX>', devtype=24776, timeout=10, name='Smart Bulb', model='LB1', manufacturer='Broadlink', is_locked=False)
broadlink.exceptions.AuthenticationError: [Errno -1] Authentication failed
>>> devices[0].is_locked
False
>>>
but when I am trying to connect to get the auth
Obtain the authentication key required for further communication:
devices[0].auth()

getting below mentioned error 
>>> devices[0].auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\broadlink\device.py", line 187, in auth
    check_error(response[0x22:0x24])
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\broadlink\exceptions.py", line 151, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: [Errno -1] Authentication failed

how I can solve this issue ?

**Comment by felipediel** [comment]
Add the device with the Broadlink app and unlock the bulb there. I don't know why it is showing as unlocked. Perhaps they changed the protocol (again). Mind doing a quick test?
```python3
import socket

with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as conn:
	packet = bytearray(0x30)
	packet[0x26] = 6
	conn.sendto(packet, ('192.168.0.16', 80))  # Example LB1 IP address
	conn.settimeout(5)
	print(conn.recvfrom(2048))
```
What is the output?
