### ISSUE TITLE
可以添加CN的sp4吗

### ISSUE THREAD

**Issue by 15959626783** [mjg59/python-broadlink#576]
0x7568: (sp4, "SP4L-CN", "Broadlink"),

**Comment by KTibow** [comment]
Most people who support you here speak English. Could you speak in that language instead?

**Comment by 15959626783** [comment]
Sorry, I would like to add a Chinese version of sp4l    
I'll add them manually
_ init_ .py
So I don't have to download the file to the local
I pulled the number

**Comment by felipediel** [comment]
謝謝你
