### ISSUE TITLE
SCB1E missing energy

### ISSUE THREAD

**Issue by shyrwall** [mjg59/python-broadlink#578]
Hi

SCB1E is mapped to sp4b but sp4b does not contain an energy class. 

Copying get_energy function from sp3s results in : 

broadlink.exceptions.StorageError: [Errno -5] The device storage is full

**Comment by shyrwall** [comment]
Hmm. Maybe get_energy was deprecated? :) get_state worked.

**Comment by KTibow** [comment]
This is an error talked about many times before. What is the get_energy source?

**Comment by shyrwall** [comment]
Sorry for late reply. Yes I saw it was talked about before but opened the issue because it looked like it didn't have a way to get the watt usage etc but it seems it was just baked into get_state() so maybe get_energy() was deprecated for this device. 

Anyway. Everything working so closing the issue.
