### ISSUE TITLE
Is my RM Mini 3 an `rmmini` or an `rmminib` device?

### ISSUE THREAD

**Issue by gurbyz** [mjg59/python-broadlink#588]
I want to submit a PR for my new RM Mini 3 devices which give an 'Unsupported device 0x6507' error when integrating in Home Assistant. I want to add the 0x6507 device in `__init__.py` but I have to know first if it is a plain (?) `rmmini` or a more special (?) `rmminib` device. How do I know?

Bottom of the device says: Model RM mini 3
Color: orange with black top
FCC ID on the package: 2ACDZ-RMMINI3-RM
There is already a 'near' device 0x6508 in the `__init__.py`, but I'm not sure that's enough to decide.

**Comment by felipediel** [comment]
This is an rmminib. I added it for you. Thank you!

**Comment by gurbyz** [comment]
Superfast! Thx a lot.

**Comment by felipediel** [comment]
You're welcome!
