### ISSUE TITLE
RM4C pro not supported

### ISSUE THREAD

**Issue by kst84** [mjg59/python-broadlink#596]
Can we please have a RM4C pro added ? 
[homeassistant.components.broadlink.config_flow] Unsupported device: 0x6184

**Comment by im0t0** [comment]
Home Assistant core-2021.7.0

2021-07-08 11:54:00 ERROR (MainThread) [homeassistant.components.broadlink.config_flow] Unsupported device: 0x6184. If it worked before, please open an issue at https://github.com/home-assistant/core/issues

**Comment by im0t0** [comment]
core-2021.8.0
Still not added.

**Comment by DutchessNicole** [comment]
I would also love to have this added to the library. Do you need any info from us?

**Comment by Pasha1402** [comment]
+1. Good alternative to more expensive and huge RM4 Pro.

**Comment by DutchessNicole** [comment]
in case of HassOS that would be /usr/local/lib/python3.9/site-packages/broadlink/__init__.py

**Comment by felipediel** [comment]
Thank you! :rocket:

**Comment by mikkelsiggaard** [comment]
@felipediel Why was this closed? 
It still needs work in code to be supported?

**Comment by felipediel** [comment]
Hi. It's already supported.

**Comment by mikkelsiggaard** [comment]
So this step is no longer necessary? 

> For now HA users can modify __init__.py in HA root PY folder /lib/python3.8/site-packages/broadlink/__init__.py by adding under SUPPORTED_TYPES section the following line 0x6184: (rm4pro, "RM4C pro", "Broadlink"),

**Comment by felipediel** [comment]
Nope
