### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by lepipo** [mjg59/python-broadlink#6]
Hi, 
first, i'll thanks to you script, it's amazing it's work with my (new) broadlink RM-PRO and on raspberry pi2! 

I'll ask you something, can we get the temperature sensor value with this script? i'll plan to integrated it on jeedom or domoticz.

Regards

**Comment by mjg59** [comment]
Does the RM-PRO have its own temperature sensor? If so, I'll try to add support.

**Comment by lepipo** [comment]
Yes, the RM-PRO have its own temperatur sensor. It will be very cool if you can add this support. In fact, i'll can schedule to start my air conditioner if the temperature is up to.. i hope you can find the parameter !
many thanks

**Comment by mjg59** [comment]
Added in the latest commit. Thanks!

**Comment by lepipo** [comment]
Hi, i'm newby on python, i see your change in your script, but i don't know how can i get the temperature value ! i do print device.check_temperature() but i have always the same answer : "none" what's wrong?

**Comment by aldodemi** [comment]
With "device.check_temperature()" I've a return value but, let me say, is "strange": 120.8 from RM2 and 168.3 from A1, not celsius but not also Fahrenheit.....

**Comment by jcoudrais** [comment]
For me, it's ok, I get 25.1 also °C

**Comment by aldodemi** [comment]
@jcoudrais , can you please share your script to retrieve the temperature? Thanks

**Comment by jcoudrais** [comment]
Here : 
import broadlink
device = broadlink.rm2()
device.discover()
device.auth()
print device.check_temperature()
25.1

**Comment by aldodemi** [comment]
like mine, except for the result: 120.8!!!!!
Thank you.....
