### ISSUE TITLE
Add support for Broadlink LB27 R1 0xA5F7

### ISSUE THREAD

**Issue by Innuendo1975** [mjg59/python-broadlink#639]
Please add support for a new code of LB27 R1
`0xA5F7: ("LB27 R1", "Broadlink")`

seems to be compatible with the current implementation of _broadlink.light.lb2_

**Comment by madmat777** [comment]
I also have a LB27 R1 that has a code of 
0x644C: ("LB27 R1", "Broadlink")

**Comment by felipediel** [comment]
Thank you!
