### ISSUE TITLE
Support for Broadlink RM4 pro 0x5213

### ISSUE THREAD

**Issue by chpkt** [mjg59/python-broadlink#646]
Please add support for a Broadlink RM4 pro, code `0x5213`

thanks!

**Comment by jvcsw** [comment]
Hi,

how to find the code 0x5213 in the device?

I have the same problem, but I don't know if I have this exact code.

Thanks

**Comment by chpkt** [comment]
add your Broadlink device to HA, after you got the "Device not supported" error, go to HA logs and you should find a similar error:
```
Unsupported device: 0x5213. If it worked before, please open an issue at https://github.com/home-assistant/core/issues
09:17:03 – (ERROR) Broadlink
```

**Comment by jvcsw** [comment]
Yes, same problem here. 

Big disappointment. I really wanted to configure the broadlink remote control and the devices, this was not what I expected.

**Comment by felipediel** [comment]
Added. It comes in the next release. Thank you!

**Comment by jvcsw** [comment]
In the next release of Home Assistant or python-broadlink? Or both?

Thank you very much!

**Comment by felipediel** [comment]
Both

**Comment by jvcsw** [comment]
Hi @felipediel,

this message appears in the last version 2022.2 again:

"Unsupported device: 0x5213"

It doesn't work in the new version as you commented. 

Thanks

**Comment by felipediel** [comment]
Hi. This device will be released in version 0.18.1 of this module, only then will we be able to create an update for Home Assistant.

**Comment by jvcsw** [comment]
Ok, but, do you know when this will be? 
Because if it doesn't work for me I have to return the Broadlink product.

**Comment by felipediel** [comment]
Soon
