### ISSUE TITLE
New rm4 pro device 

### ISSUE THREAD

**Issue by okkies** [mjg59/python-broadlink#652]
rm4pro: {
        0x5213 : ("RM4 pro", "Broadlink"),

i just added this one manually to my local script, can it be merged ? 
sorry, i never used github as a developer, so no clue how i could have done this myself

**Comment by felipediel** [comment]
Already added to new_product_ids, it will be available soon, thank you!

**Comment by Doublemyst** [comment]
Hi there, any updates, or maybe a rough timeline when it will be available? Tried to add broadlink to homeassistant, but got the message "Unsupported device: 0x5213. If it worked before, please open an issue at https://github.com/home-assistant/core/issues". Thanks!
