### ISSUE TITLE
type of device installed to? 

### ISSUE THREAD

**Issue by Matt8119** [mjg59/python-broadlink#66]
i was reading the readme and it doesnt mention or i couldnt find what type of device i install this file to.  is this installed on RPI or a different platform?

THanks,

matthew

**Comment by mob41** [comment]
You mean getting the device type? Or where the library is installed to?

The library can be either installed on Windows and Linux, where RPi is running on Linux (Debian).

**Comment by Matt8119** [comment]
Installing it on a RPI running linux is exactly what I was looking to do. Perfect, thanks!

**Comment by mob41** [comment]
Uh.... what you mean? I don't understand.

**Comment by johado** [comment]
I use it in a RPI 3. Run python setup.py build and then
sudo pyhon setup.py install

**Comment by mob41** [comment]
>I use it in a RPI 3. Run python setup.py build and then
sudo pyhon setup.py install

It should be `python setup.py install`. Just take a note about that 😄

**Comment by johado** [comment]
Sorry about that - writing on a phone (with Swedish autocorrection  to make things even worse)

**Comment by mjg59** [comment]
It should work on any system that has Python available.
