### ISSUE TITLE
Broadlink for Windows

### ISSUE THREAD

**Issue by helgovic** [mjg59/python-broadlink#663]
I have created a Windows app, using this repository.

With this app you can control Broadlink WiFi devices.

   Manage IR and RF devices and buttons.
   Manage Broadlink WiFi devices.
   Create macros that executes commands from any device.
   Create timers (Repeat every x days/hours/minutes/seconds, Every day x hours/minutes before/after sunrise/sunset) that executes 
   commands/macros.
   
Teach IR and RF codes. Send codes or macros from app or use the command line interface. Data is stored in SQLite database.

Sharing of device codes:

I have created a cloud database, to share device codes.  
If you want to utilize the shared database from another platform/app, you can send a mail to helgovic@hotmail.dk to get database specifics

Have a look [Broadlink for windows](https://github.com/helgovic/Broadlink-for-Windows)

**Comment by zDEFz** [comment]
This did absolutely not work for me

**Comment by felipediel** [comment]
Thank you!
