### ISSUE TITLE
BrodLink RM4 Pro IR-RF U.C

### ISSUE THREAD

**Issue by sevagjb** [mjg59/python-broadlink#664]
i bot new Broadlink RM4 pro , its not supported,
when i add the Integration i receive this message:
Aborted
Device not supported,
This is device datils:
Device info : S/N code
PID ; 00000000000000000000000013520000
DID : 00000000000000000000ecObae6edc02
loT Cloud : World
MAC: XX:XX:XX:XX:XX:XX
Firmware :
V62092
Device IP : ***@***.***
Data Cloud : European server
SDK : 2.17
Plug-in version : 1.6.7.2
Routine traits : Trigger

Connector Type: ‎Wi-Fi, Radio Frequency
ASIN: ‎B083LLLVPN

can you help my please ?
Thanks

**Comment by felipediel** [comment]
Thanks! Already added, it will be available soon.
