### ISSUE TITLE
Hysen HY02-B05WH

### ISSUE THREAD

**Issue by spartakos87** [mjg59/python-broadlink#670]
Hello, 
First of all, I want to ask if this device is supported? I see only the device Hysen HY02B05H.
In case is supported I have a problem discovering it. I have connected in my lan with the official application "Smart Life" and then I can't discover it. But I can control it with the app. Do I need to follow some other steps to discover the device?
Thanks

**Comment by felipediel** [comment]
One possibility is that the device is locked. Check if there is an option to unlock it in the Smart Life app. You can also try to reset the device and provision the Wi-Fi network with this module.

**Comment by linrongfeng77** [comment]
Your device uses the "Smart Life" app. The WiFi module should be Tuya WiFi module, not broadlink WiFi module.

**Comment by linrongfeng77** [comment]
Your device uses the "Smart Life" app. The WiFi module should be Tuya WiFi module, not broadlink WiFi module.
