### ISSUE TITLE
Can we use learing code with arduino? (RM4 mini)

### ISSUE THREAD

**Issue by spartakos87** [mjg59/python-broadlink#675]
Have anyone try to use learning codes from RM4 mini with arduino?
My idea is to use rm4 mini to learning code of my AC and then use arduino or nodemcu to transmit these codes
Any idea how to achieve this?
Thanks

**Comment by bengtmartensson** [comment]
Use `--durations`:

     ./broadlink_cli --device @device --learn --durations
    Learning...
    +9688 -4827 +624 -591 +624 -591 +591 -624 +591 -624 +591 -624 +591 -591 +624 -591 +591 -1839 +591 -1806 +624 -1806 +591 -1839 +591 -1839 +591 -1806 +591 -1839 +591 -1839 +591 -1806 +591 -1839 +591 -1839 +591 -1806 +624 -1806 +591 -1839 +591 -624 +591 -591 +591 -624 +591 -624 +591 -624 +591 -624 +591 -591 +624 -591 +591 -1839 +591 -1806 +624 -1806 +591 -41805 +9655 -2430 +591 -103479 +9655 -2430 +624 -109456

These "durations" are in micro seconds and can be used in other tools, for example IrScrutinizer or (Arduino) IRremote.

Unfortunately, there is a problem with the current version; producing some errors. I will submit a PR fixing this, but in the meantime, just ignore the errors.
