### ISSUE TITLE
Support for RM4-PRO - 0x520b

### ISSUE THREAD

**Issue by pereirapleandro** [mjg59/python-broadlink#679]
When I try to configure my Broadlink RM4 PRO I receive an error `Unsupported device: 0x520b`.
Please, could you add this new version of Universal Remote RM4 PRO?
Thank you!

**Comment by Mr-Beat** [comment]
I have the same problem: 
> 2022-05-03 11:42:23 ERROR (MainThread) [homeassistant.components.broadlink.config_flow] Unsupported device: 0x520b. If it worked before, please open an issue at https://github.com/home-assistant/core/issues

**Comment by pereirapleandro** [comment]
The new RM4 Pro device was included on this PR https://github.com/mjg59/python-broadlink/pull/673 24 days ago.

**Comment by Mr-Beat** [comment]
> +1 @felipediel ❤

**Comment by felipecrs** [comment]
+1, I just bought two 0x520b and can't wait to integrate them in Home Assistant!

**Comment by pereirapleandro** [comment]
@felipediel Could you help us, please? 🙏

**Comment by NaturalSelectionPlayer** [comment]
Commit was created 1 month ago, but checks with current commit isnt pass well. And now we awaits correct code with last merge to master Br. There a lot of new devices IDs. Thx all.

**Comment by eduardoll00** [comment]
+1 ! Waiting for the update

**Comment by felipecrs** [comment]
@mjg59, @felipediel do you guys need any help? Like writing changelog, whatever? If so, let me know, I can try to help.

**Comment by felipediel** [comment]
Hi guys, I just finished the update, it will be available in Home Assistant soon.

Thanks @felipecrs, this one is gone, but feel free to create a PR whenever you like :+1:
