### ISSUE TITLE
 LB27 R1 0x644C - Home Assistant Issue

### ISSUE THREAD

**Issue by manunited10** [mjg59/python-broadlink#688]
Hi.
I added some comments at the bottom of [this page](https://github.com/mjg59/python-broadlink/pull/644). It didn't get any attention so I created a new topic here.
There's a problem with my light which is recently added to this repo and Home Assistant. Honestly I'm not sure if it was a good idea to talk about here - but I did anyway! 
Thanks.

**Comment by manunited10** [comment]
@felipediel any luck this could get an attention? 🤞

**Comment by felipediel** [comment]
Hi, thanks for looking into this. I confirm the issue exists, but I'm short on time to work on it at the moment, if you can send a PR to Home Assistant with the changes it will be of great help

**Comment by manunited10** [comment]
> Hi, thanks for looking into this. I confirm the issue exists, but I'm short on time to work on it at the moment, if you can send a PR to Home Assistant with the changes it will be of great help

I suspect it may fix my light but break others.

**Comment by felipediel** [comment]
All lights have the same issue. There was a PR to fix them a while ago, but it was abandonned.

**Comment by manunited10** [comment]
> All lights have the same issue. There was a PR to fix them a while ago, but it was abandoned.

I made a PR in homeassistant, but I made a bad mistake. Could you please delete it there? it's important. Thanks.

**Comment by felipediel** [comment]
Sorry, there is no way to delete a PR. Why did you close it?

**Comment by felipediel** [comment]
Fixed, thank you!
