### ISSUE TITLE
RF Code too long?  Breaks python-broadlink?

### ISSUE THREAD

**Issue by luketoh** [mjg59/python-broadlink#69]
Hi all,

I noticed that if I captured an RF code that is pretty long, and then try to send the code to the RM3, the script crashes.  But if I send an IR code (which is shorter), it works.

It appears that the python-broadlink can't accept a longer RF string?  Am I correct?  Is there a fix for this?

pi@hassbian:/home/rmcontrol $ cat codes/test.txt
b20184030917190719070a1709170a160a00010819070a1709171908091719070a1719070a17180809171908091709181808091719080917091709181907190819071907190819070a161a07190709180917091709000109190709170a1718080918190709171908091719070a1719070918091719070a1719070a160a170917190819071907190819071908091719071908091709170a1709000108190809170917190809171908091719070a1719070918180809170a1719070918180809170a1709171907190819071908190719070a17190719070a1709170a160900011018080918091718080918190709171908091719080917190709180917190709181907091809170917190818081907190819071908091719071a07091709170a170900010f19070a17091719070a171808091818080917190809171907091809171908091719070a1709170a1718081907190819071908180809171908190709170a1709170900010f19070a17091719070a1719070a17190709171a07091719070a1709171908091719070a170918091719071907190819071908180809171908190709170a1709170900010f19070a1709171908091719070a1719070917190809171908091709171908091719070a1709170a1718081907190819071908190709171908180809170a1709170900010f190809170917190809171908091719070a16190809171a0709170917190809171908091709170a17190719071a0719071908180809171908190709170a1709170900010f1908091709181808091719070a1719070a1719070917190809170a1719070917190809170a17091719071908180819081808190709171a0719070a17091709170900010f190809170918180809171908091719070a1719070a17190709170a1719070918180809170a1709171908180819071908190719070a17190719070a1709170a160a00010e1908091709181907091719080917190809171908091719070918091719070a1719070918091709171908180819071a07190719070a1719071908091709170a160a00010f19070918091719070918190709171a0709171908091719070a17091719070a1719070a1709170917190819071908190719071908091719071a0709170a1709170900010f1907091809171908091719070a171907091719080917190809170918180809171908091709170a17190719071a0719071908190709171a0719070a1709170917090005dc00000000pi@hassbian:/home/rmcontrol $ python sendtest.py codes/test.txt
Connecting to Broadlink device....
Connected....
Traceback (most recent call last):
  File "sendtest.py", line 30, in <module>
    device.send_data(myhex.decode('hex'))
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 450, in send_data
    self.send_packet(0x6a, packet)
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 250, in send_packet
    response = self.cs.recvfrom(1024)
socket.timeout: timed out

Here's the code I used for sendtest.py

#!/usr/bin/python

import broadlink
import time
import sys

try:
    fileName = sys.argv[1]
except IndexError:
    fileName = 'null'

if fileName == 'null':
   print "Error - no file name parameter suffixed"
   sys.exit()
else:

   device = broadlink.rm(host=("192.168.0.111",80), mac=bytearray.fromhex("B5430DFBCCC4"))

print "Connecting to Broadlink device...."
device.auth()
#time.sleep(1)
print "Connected...."
#time.sleep(1)
device.host

file = open(fileName, 'r')

myhex = file.read()

device.send_data(myhex.decode('hex'))
print "Code Sent...."

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/486. Thank you!
