### ISSUE TITLE
Feature Request: Expose discovery values in Device class?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mjg59/python-broadlink#697]
Feature Request: Expose discovery values in Device class?  The only way to retrieve discovered information is via a canned format?  _repr_ or _str_?

You can pull firmware version, temperature, humidity, but you can't pull name, type, IP, port, or MAC address?  Device class could be changed to allow for more information to be pulled explicitly.

**Comment by felipediel** [comment]
These methods are not necessary, we can query the properties directly. Instead of theDevice.get_manufacturer() we use theDevice.manufacturer, for example.

**Comment by Jibun-no-Kage** [comment]
Ah... that works, thanks.
