### ISSUE TITLE
Can Broad Link RM4 Mini (for example) Query device for power state?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mjg59/python-broadlink#699]
Can Broad Link RM4 Mini (for example) Query device for power state?  For example with CEC, you can ask the device for its power state, on or off/standby.  But I have not seen any examples of doing the same via Broad Link devices?  Is such possible?

**Comment by felipediel** [comment]
Not possible. If you have a Raspberry Pi, you can install Home Assistant and combine the HDMI-CEC integration with the Broadlink integration to achieve the result you want.

**Comment by Jibun-no-Kage** [comment]
Humm... right now I am just using a simple ping to determine if the RM4 is on the network.  That works but is limited.

**Comment by felipediel** [comment]
Ah, I understand now. I though you wanted to query the power state of the TV. A ping is ok to check the device, you could also use check_temperature() or any method that queries the state.
