### ISSUE TITLE
cypher AES, pyaes

### ISSUE THREAD

**Issue by jcoudrais** [mjg59/python-broadlink#7]
Hi,

this is an issue only to me, but it will help me a lot...

So, should I use Pyaes instead of pycrypto ?
 if so, what to change in __init ?

Thank you for your help.

**Comment by mjg59** [comment]
Replace

from Crypto.Cipher import AES

with

import pyaes

and replace:

      aes = AES.new(str(self.key), AES.MODE_CBC, str(self.iv))

with

      aes = pyaes.AESModeOfOperationCBC(str(self.key) iv = str(self.iv))

I *think* that should work, but I haven't tested.

**Comment by jcoudrais** [comment]
Hi, thank you for this try, but it's ok now with pycrypto, my firmware's nas builder built the pycrypto for me...

That's ok.
