### ISSUE TITLE
SCB1E energy monitor doesn't work

### ISSUE THREAD

**Issue by vrm42** [mjg59/python-broadlink#755]
Hello, I've got an SCB1E device and I can turn it on/off with cli but can't read energy consumption.

AttributeError: 'sp4' object has no attribute 'get_energy'

In switch.py there is no 'get_energy' defined for SP4 devices. In __init__.py SCB1E is listed in SP4 category.
I tried to copy the 'get_energy' parts from other devices to the sp4 section but it didn't work.

Please help.
Thanks,
vrm

**Comment by felipediel** [comment]
You should use the sp4b class and the get_state() function.
