### ISSUE TITLE
how to recognize different SmartPlug2 same series ?

### ISSUE THREAD

**Issue by zyklop70** [mjg59/python-broadlink#76]
Hello,
i have two SM2 smart plugs. Standalone both works fine. 
But both at same time are not secure at discover time the sequence is not the same all the time.
Depending on which device is discovered first, the sequence is not even the same.
Is there a way to define the device absolete with (for example mac address) in python script ?
My actual script to switch on/off looks like this:

#!/usr/bin/python
import broadlink
import time
devices = broadlink.discover(timeout=2)
plug = devices[0]
devices[0].auth()
devices[0].set_power(True)  # or (False) for turn off

Thanks

**Comment by johado** [comment]
You can try out the johado_branch in the johado fork. 
cli/johado_cli can do what you want.
First modify the local_ip variabler to match your setup, and run it once without arguments which will detect your devices and save the info in a json file. 
If you havent named your devices using the app you should do that, then you use that name to referens till tour device when ändring setpower commands etc.

**Comment by zyklop70** [comment]
now i installed the cli from your package, but no json file was createt  and i dont understand how to send command "power on" to a smart plug using this command for example:

python /home/pi/python-broadlink-master/cli/johado_cli -d 192.168.x.x  -c setpower=1

will produce error:
line 139 and line 108 while discover
Attribut Error: ´module object´has no attribute ´dev2devinfo´

What i am doing wrong ?!

**Comment by johado** [comment]
Have you installed the library from my fork as well?

**Comment by zyklop70** [comment]
yes.....installed...

Am 10.03.2017 7:27 vorm. schrieb "johado" <notifications@github.com>:

**Comment by zyklop70** [comment]
problem solved....
i forgot to rename ALL devices via App...so it hangs at the first devices name.....my son plugged a second smartplug without my knowing ...sorry....
Now it works like a charme !!! Respect !! Great Work !!!
