### ISSUE TITLE
Add support for torando ACs

### ISSUE THREAD

**Issue by thewh1teagle** [mjg59/python-broadlink#774]
Please if possible add support for these ACs
`Tornado Iska INV 12 X WIFI EU` (2023)

And 
`Tornado Iska A-16 X WIFI` (2021)

The 2021 one discoverable by `broadlink_cli` but the 2023 one isn't even discoverable.
I can see it's connected to the network.
Also, in tornado app - the 2023 version doesn't work from tornado app when no internet on my network

**Comment by felipediel** [comment]
Tornado Iska A-16 X WIFI is added. Maybe Tornado Iska INV 12 X WIFI EU has a different firmware. If it cannot be controlled locally, it is not supoorted by this API.
