### ISSUE TITLE
Maintenance of this library

### ISSUE THREAD

**Issue by Danielhiversen** [mjg59/python-broadlink#83]
@mjg59 : Are you planning to maintain this library?

You have not reviewed or merged any pull request for a long time.
If you do not have any plan to maintain it, I am planning to start using my fork for Home Assistant.

**Comment by mjg59** [comment]
Yeah I'm way behind. I can review some stuff over the weekend, but I'm also happy to just make you a co-maintainer?

**Comment by McJono** [comment]
@Danielhiversen it would be great if you could input it into Home Assistant, if mjg59 allows. Atm the workaround is rather annoying.

**Comment by Danielhiversen** [comment]
@mjg59 
I understand your limited time.
I also have a limited time to spend on these project.
If you make me a co-maintainer I can review and test bug fixes and smaller improvements.

**Comment by mjg59** [comment]
I've uploaded 0.4 to pypi with all the outstanding PRs merged
