### ISSUE TITLE
device.check_power() always returns True

### ISSUE THREAD

**Issue by xxLeoxx** [mjg59/python-broadlink#85]
I'm using a SP2 device and switching on and off works perfectly. However device.check_power() always returns true, even when the device is turned off.

**Comment by Danielhiversen** [comment]
Are you using the latest version of the library? 
https://github.com/mjg59/python-broadlink/pull/72/files

**Comment by xxLeoxx** [comment]
Shame on me, I didn't install the update. Thank you anyway!
