### ISSUE TITLE
import broadlink, configparser ImportError: No module named broadlink

### ISSUE THREAD

**Issue by samsonrosen** [mjg59/python-broadlink#89]
Hello,

I've suddenly just started getting this error:

```
import broadlink, configparser
ImportError: No module named broadlink
```

**Comment by mob41** [comment]
Have you done this? You have to install broadlink module to import it!

<code>git clone https://github.com/mjg59/python-broadlink.git</code>

<code>cd python-broadlink</code>

<code>python setup.py install</code>

**Comment by mob41** [comment]
Or you mean "Suddenly" that you didn't experience as it is already running for a time and suddenly jumps out an error?

**Comment by samsonrosen** [comment]
Hi,

I just removed everything and followed your instructions and it all seems to be good now!

Thanks,l

Sam
