### ISSUE TITLE
A1 Temperature error

### ISSUE THREAD

**Issue by muriloyvens** [mjg59/python-broadlink#98]
i am trygin to retreive temperature and is now working. i tryed with python 3 3.4 3.5
alway return the same:

./broadlink_cli --device "0x2712 192.168.0.52 b4430dfbedd6" --temperature
Traceback (most recent call last):
  File "./broadlink_cli", line 27, in <module>
    mac = bytearray.fromhex(values[2])
TypeError: fromhex() argument 1 must be unicode, not str

**Comment by felipediel** [comment]
This issue no longer exists I suppose. If you have any problem, please reopen it.
